// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Permission) Default() {
}

func (x *CreatePermissionRequest) Default() {
}

func (x *CreatePermissionResponse) Default() {
}

func (x *UpdatePermissionRequest) Default() {
}

func (x *UpdatePermissionResponse) Default() {
}

func (x *DeletePermissionRequest) Default() {
}

func (x *DeletePermissionResponse) Default() {
}

func (x *GetPermissionRequest) Default() {
}

func (x *GetPermissionResponse) Default() {
}

func (x *ListPermissionRequest) Default() {
}

func (x *ListPermissionResponse) Default() {
}

func (x *ListPermissionTreeRequest) Default() {
	if x.Level == nil {
		v := int32(0)
		x.Level = &v
	}
}

func (x *ListPermissionTreeResponse) Default() {
}

func (x *PermissionTreeNode) Default() {
}
