// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: apiserver/v1/role.proto

package v1

import (
	_ "github.com/onexstack/protoc-gen-defaults/defaults"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role 表示角色信息
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示角色 ID
	RoleID string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	// roleName 表示角色名称
	RoleName string `protobuf:"bytes,2,opt,name=roleName,proto3" json:"roleName,omitempty"`
	// roleCode 表示角色编码
	RoleCode string `protobuf:"bytes,3,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	// description 表示角色描述
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// status 表示角色状态（0=启用,1=禁用）
	Status int32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	// sortOrder 表示排序序号
	SortOrder int32 `protobuf:"varint,6,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	// createdAt 表示创建时间
	CreatedAt int64 `protobuf:"varint,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     int64 `protobuf:"varint,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_apiserver_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *Role) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *Role) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Role) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Role) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Role) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateRoleRequest 表示创建角色请求
type CreateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleName 表示角色名称
	RoleName string `protobuf:"bytes,1,opt,name=roleName,proto3" json:"roleName,omitempty"`
	// roleCode 表示角色编码
	RoleCode string `protobuf:"bytes,2,opt,name=roleCode,proto3" json:"roleCode,omitempty"`
	// description 表示角色描述
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// sortOrder 表示排序序号
	SortOrder     *int32 `protobuf:"varint,4,opt,name=sortOrder,proto3,oneof" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRoleRequest) GetRoleCode() string {
	if x != nil {
		return x.RoleCode
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

// CreateRoleResponse 表示创建角色响应
type CreateRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示新创建的角色 ID
	RoleID        string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoleResponse) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

// UpdateRoleRequest 表示更新角色请求
type UpdateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示角色 ID
	// @gotags: uri:"roleID"
	RoleID string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty" uri:"roleID"`
	// roleName 表示可选的角色名称
	RoleName *string `protobuf:"bytes,2,opt,name=roleName,proto3,oneof" json:"roleName,omitempty"`
	// description 表示可选的角色描述
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// status 表示可选的角色状态（0=启用,1=禁用）
	Status *int32 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// sortOrder 表示可选的排序序号
	SortOrder     *int32 `protobuf:"varint,5,opt,name=sortOrder,proto3,oneof" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoleRequest) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *UpdateRoleRequest) GetRoleName() string {
	if x != nil && x.RoleName != nil {
		return *x.RoleName
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateRoleRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

// UpdateRoleResponse 表示更新角色响应
type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{4}
}

// DeleteRoleRequest 表示删除角色请求
type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示角色 ID
	// @gotags: uri:"roleID"
	RoleID        string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty" uri:"roleID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRoleRequest) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

// DeleteRoleResponse 表示删除角色响应
type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{6}
}

// GetRoleRequest 表示获取角色请求
type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示角色 ID
	// @gotags: uri:"roleID"
	RoleID        string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty" uri:"roleID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleRequest) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

// GetRoleResponse 表示获取角色响应
type GetRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role 表示返回的角色信息
	Role          *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

// ListRoleRequest 表示角色列表请求
type ListRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pageToken 表示分页游标
	// @gotags: form:"page_token"
	PageToken string `protobuf:"bytes,1,opt,name=pageToken,proto3" json:"pageToken,omitempty" form:"page_token"`
	// pageSize 表示每页数量
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" form:"page_size"`
	// status 表示状态过滤（0=启用,1=禁用，留空表示全部）
	// @gotags: form:"status"
	Status *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	// keyword 表示搜索关键字
	// @gotags: form:"keyword"
	Keyword       *string `protobuf:"bytes,4,opt,name=keyword,proto3,oneof" json:"keyword,omitempty" form:"keyword"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleRequest) Reset() {
	*x = ListRoleRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleRequest) ProtoMessage() {}

func (x *ListRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleRequest.ProtoReflect.Descriptor instead.
func (*ListRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoleRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRoleRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRoleRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListRoleRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

// ListRoleResponse 表示角色列表响应
type ListRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示总角色数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// roles 表示角色列表
	Roles []*Role `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// pageToken 表示下一页游标
	PageToken     string `protobuf:"bytes,3,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResponse) Reset() {
	*x = ListRoleResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResponse) ProtoMessage() {}

func (x *ListRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResponse.ProtoReflect.Descriptor instead.
func (*ListRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{10}
}

func (x *ListRoleResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListRoleResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRoleResponse) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// AssignPermissionsToRoleRequest 表示给角色分配权限请求
type AssignPermissionsToRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示角色 ID
	// @gotags: uri:"roleID"
	RoleID string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty" uri:"roleID"`
	// permissionIDs 表示权限 ID 列表
	PermissionIDs []string `protobuf:"bytes,2,rep,name=permissionIDs,proto3" json:"permissionIDs,omitempty"`
	// mode 表示分配模式（override=覆盖, append=追加）
	// @gotags: form:"mode"
	Mode          *string `protobuf:"bytes,3,opt,name=mode,proto3,oneof" json:"mode,omitempty" form:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionsToRoleRequest) Reset() {
	*x = AssignPermissionsToRoleRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionsToRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionsToRoleRequest) ProtoMessage() {}

func (x *AssignPermissionsToRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionsToRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionsToRoleRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{11}
}

func (x *AssignPermissionsToRoleRequest) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

func (x *AssignPermissionsToRoleRequest) GetPermissionIDs() []string {
	if x != nil {
		return x.PermissionIDs
	}
	return nil
}

func (x *AssignPermissionsToRoleRequest) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

// AssignPermissionsToRoleResponse 表示给角色分配权限响应
type AssignPermissionsToRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionsToRoleResponse) Reset() {
	*x = AssignPermissionsToRoleResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionsToRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionsToRoleResponse) ProtoMessage() {}

func (x *AssignPermissionsToRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionsToRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignPermissionsToRoleResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{12}
}

// GetRolePermissionsRequest 表示获取角色权限请求
type GetRolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roleID 表示角色 ID
	// @gotags: uri:"roleID"
	RoleID        string `protobuf:"bytes,1,opt,name=roleID,proto3" json:"roleID,omitempty" uri:"roleID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRequest) Reset() {
	*x = GetRolePermissionsRequest{}
	mi := &file_apiserver_v1_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequest) ProtoMessage() {}

func (x *GetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{13}
}

func (x *GetRolePermissionsRequest) GetRoleID() string {
	if x != nil {
		return x.RoleID
	}
	return ""
}

// GetRolePermissionsResponse 表示获取角色权限响应
type GetRolePermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissions 表示权限列表（树形结构）
	Permissions   []*PermissionTree `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResponse) Reset() {
	*x = GetRolePermissionsResponse{}
	mi := &file_apiserver_v1_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponse) ProtoMessage() {}

func (x *GetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{14}
}

func (x *GetRolePermissionsResponse) GetPermissions() []*PermissionTree {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// PermissionTree 表示权限树节点
type PermissionTree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionID 表示权限 ID
	PermissionID string `protobuf:"bytes,1,opt,name=permissionID,proto3" json:"permissionID,omitempty"`
	// permissionName 表示权限名称
	PermissionName string `protobuf:"bytes,2,opt,name=permissionName,proto3" json:"permissionName,omitempty"`
	// permissionCode 表示权限编码
	PermissionCode string `protobuf:"bytes,3,opt,name=permissionCode,proto3" json:"permissionCode,omitempty"`
	// resourceType 表示资源类型（menu=菜单, button=按钮）
	ResourceType string `protobuf:"bytes,4,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	// resourcePath 表示资源路径
	ResourcePath string `protobuf:"bytes,5,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	// action 表示操作（GET/POST 等）
	Action string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	// children 表示子权限列表
	Children []*PermissionTree `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	// assigned 表示是否已分配
	Assigned      bool `protobuf:"varint,8,opt,name=assigned,proto3" json:"assigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTree) Reset() {
	*x = PermissionTree{}
	mi := &file_apiserver_v1_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTree) ProtoMessage() {}

func (x *PermissionTree) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTree.ProtoReflect.Descriptor instead.
func (*PermissionTree) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_role_proto_rawDescGZIP(), []int{15}
}

func (x *PermissionTree) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

func (x *PermissionTree) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *PermissionTree) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *PermissionTree) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PermissionTree) GetResourcePath() string {
	if x != nil {
		return x.ResourcePath
	}
	return ""
}

func (x *PermissionTree) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionTree) GetChildren() []*PermissionTree {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *PermissionTree) GetAssigned() bool {
	if x != nil {
		return x.Assigned
	}
	return false
}

var File_apiserver_v1_role_proto protoreflect.FileDescriptor

const file_apiserver_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x17apiserver/v1/role.proto\x12\fapiserver.v1\x1a,github.com/onexstack/defaults/defaults.proto\"\xea\x01\n" +
	"\x04Role\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\x12\x1a\n" +
	"\broleName\x18\x02 \x01(\tR\broleName\x12\x1a\n" +
	"\broleCode\x18\x03 \x01(\tR\broleCode\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1c\n" +
	"\tsortOrder\x18\x06 \x01(\x05R\tsortOrder\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\b \x01(\x03R\tupdatedAt\"\xba\x01\n" +
	"\x11CreateRoleRequest\x12\x1a\n" +
	"\broleName\x18\x01 \x01(\tR\broleName\x12\x1a\n" +
	"\broleCode\x18\x02 \x01(\tR\broleCode\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12(\n" +
	"\tsortOrder\x18\x04 \x01(\x05B\x05\x9aI\x02\x18\x00H\x01R\tsortOrder\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_sortOrder\",\n" +
	"\x12CreateRoleResponse\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\"\xe9\x01\n" +
	"\x11UpdateRoleRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\x12\x1f\n" +
	"\broleName\x18\x02 \x01(\tH\x00R\broleName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x05H\x02R\x06status\x88\x01\x01\x12!\n" +
	"\tsortOrder\x18\x05 \x01(\x05H\x03R\tsortOrder\x88\x01\x01B\v\n" +
	"\t_roleNameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_sortOrder\"\x14\n" +
	"\x12UpdateRoleResponse\"+\n" +
	"\x11DeleteRoleRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\"\x14\n" +
	"\x12DeleteRoleResponse\"(\n" +
	"\x0eGetRoleRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\"9\n" +
	"\x0fGetRoleResponse\x12&\n" +
	"\x04role\x18\x01 \x01(\v2\x12.apiserver.v1.RoleR\x04role\"\x9e\x01\n" +
	"\x0fListRoleRequest\x12\x1c\n" +
	"\tpageToken\x18\x01 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x04 \x01(\tH\x01R\akeyword\x88\x01\x01B\t\n" +
	"\a_statusB\n" +
	"\n" +
	"\b_keyword\"z\n" +
	"\x10ListRoleResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12(\n" +
	"\x05roles\x18\x02 \x03(\v2\x12.apiserver.v1.RoleR\x05roles\x12\x1c\n" +
	"\tpageToken\x18\x03 \x01(\tR\tpageToken\"\x8f\x01\n" +
	"\x1eAssignPermissionsToRoleRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\x12$\n" +
	"\rpermissionIDs\x18\x02 \x03(\tR\rpermissionIDs\x12&\n" +
	"\x04mode\x18\x03 \x01(\tB\r\x9aI\n" +
	"r\boverrideH\x00R\x04mode\x88\x01\x01B\a\n" +
	"\x05_mode\"!\n" +
	"\x1fAssignPermissionsToRoleResponse\"3\n" +
	"\x19GetRolePermissionsRequest\x12\x16\n" +
	"\x06roleID\x18\x01 \x01(\tR\x06roleID\"\\\n" +
	"\x1aGetRolePermissionsResponse\x12>\n" +
	"\vpermissions\x18\x02 \x03(\v2\x1c.apiserver.v1.PermissionTreeR\vpermissions\"\xba\x02\n" +
	"\x0ePermissionTree\x12\"\n" +
	"\fpermissionID\x18\x01 \x01(\tR\fpermissionID\x12&\n" +
	"\x0epermissionName\x18\x02 \x01(\tR\x0epermissionName\x12&\n" +
	"\x0epermissionCode\x18\x03 \x01(\tR\x0epermissionCode\x12\"\n" +
	"\fresourceType\x18\x04 \x01(\tR\fresourceType\x12\"\n" +
	"\fresourcePath\x18\x05 \x01(\tR\fresourcePath\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x128\n" +
	"\bchildren\x18\a \x03(\v2\x1c.apiserver.v1.PermissionTreeR\bchildren\x12\x1a\n" +
	"\bassigned\x18\b \x01(\bR\bassignedBDZBgithub.com/clin211/gin-enterprise-template/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_role_proto_rawDescOnce sync.Once
	file_apiserver_v1_role_proto_rawDescData []byte
)

func file_apiserver_v1_role_proto_rawDescGZIP() []byte {
	file_apiserver_v1_role_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_role_proto_rawDesc), len(file_apiserver_v1_role_proto_rawDesc)))
	})
	return file_apiserver_v1_role_proto_rawDescData
}

var file_apiserver_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apiserver_v1_role_proto_goTypes = []any{
	(*Role)(nil),                            // 0: apiserver.v1.Role
	(*CreateRoleRequest)(nil),               // 1: apiserver.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),              // 2: apiserver.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),               // 3: apiserver.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),              // 4: apiserver.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),               // 5: apiserver.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),              // 6: apiserver.v1.DeleteRoleResponse
	(*GetRoleRequest)(nil),                  // 7: apiserver.v1.GetRoleRequest
	(*GetRoleResponse)(nil),                 // 8: apiserver.v1.GetRoleResponse
	(*ListRoleRequest)(nil),                 // 9: apiserver.v1.ListRoleRequest
	(*ListRoleResponse)(nil),                // 10: apiserver.v1.ListRoleResponse
	(*AssignPermissionsToRoleRequest)(nil),  // 11: apiserver.v1.AssignPermissionsToRoleRequest
	(*AssignPermissionsToRoleResponse)(nil), // 12: apiserver.v1.AssignPermissionsToRoleResponse
	(*GetRolePermissionsRequest)(nil),       // 13: apiserver.v1.GetRolePermissionsRequest
	(*GetRolePermissionsResponse)(nil),      // 14: apiserver.v1.GetRolePermissionsResponse
	(*PermissionTree)(nil),                  // 15: apiserver.v1.PermissionTree
}
var file_apiserver_v1_role_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.GetRoleResponse.role:type_name -> apiserver.v1.Role
	0,  // 1: apiserver.v1.ListRoleResponse.roles:type_name -> apiserver.v1.Role
	15, // 2: apiserver.v1.GetRolePermissionsResponse.permissions:type_name -> apiserver.v1.PermissionTree
	15, // 3: apiserver.v1.PermissionTree.children:type_name -> apiserver.v1.PermissionTree
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_apiserver_v1_role_proto_init() }
func file_apiserver_v1_role_proto_init() {
	if File_apiserver_v1_role_proto != nil {
		return
	}
	file_apiserver_v1_role_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_role_proto_msgTypes[3].OneofWrappers = []any{}
	file_apiserver_v1_role_proto_msgTypes[9].OneofWrappers = []any{}
	file_apiserver_v1_role_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_role_proto_rawDesc), len(file_apiserver_v1_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_role_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_role_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_role_proto_msgTypes,
	}.Build()
	File_apiserver_v1_role_proto = out.File
	file_apiserver_v1_role_proto_goTypes = nil
	file_apiserver_v1_role_proto_depIdxs = nil
}
