// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *AssignRolesToUserRequest) Default() {
}

func (x *AssignRolesToUserResponse) Default() {
}

func (x *GetUserRolesRequest) Default() {
}

func (x *GetUserRolesResponse) Default() {
}

func (x *RemoveRoleFromUserRequest) Default() {
}

func (x *RemoveRoleFromUserResponse) Default() {
}
