// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuditLogM = "audit_log"

// AuditLogM mapped from table <audit_log>
type AuditLogM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                     // 内部主键ID（自增序列）
	UserID    string    `gorm:"column:user_id;not null;comment:操作用户UUID" json:"userId"`                                          // 操作用户UUID
	Action    string    `gorm:"column:action;not null;comment:操作类型（如role_assign、permission_deny）" json:"action"`            // 操作类型（如role_assign、permission_deny）
	Resource  *string   `gorm:"column:resource;comment:操作的资源" json:"resource"`                                                    // 操作的资源
	Details   []byte    `gorm:"column:details;comment:操作详情（JSONB格式，记录变更前后数据）" json:"details"`                              // 操作详情（JSONB格式，记录变更前后数据）
	CreatedAt time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:操作时间" json:"createdAt"`              // 操作时间
}

// TableName AuditLogM's table name
func (*AuditLogM) TableName() string {
	return TableNameAuditLogM
}
