// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMenuM = "menu"

// MenuM mapped from table <menu>
type MenuM struct {
	ID           int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                          // 内部主键ID（自增序列）
	MenuID       string     `gorm:"column:menu_id;not null;default:gen_random_uuid();comment:菜单业务唯一UUID" json:"menuId"`             // 菜单业务唯一UUID
	ParentID     *string    `gorm:"column:parent_id;comment:父菜单UUID（用于构建菜单树）" json:"parentId"`                                     // 父菜单UUID（用于构建菜单树）
	MenuName     string     `gorm:"column:menu_name;not null;comment:菜单名称" json:"menuName"`                                            // 菜单名称
	MenuCode     string     `gorm:"column:menu_code;not null;comment:菜单编码（唯一标识）" json:"menuCode"`                                // 菜单编码（唯一标识）
	MenuType     string     `gorm:"column:menu_type;not null;comment:菜单类型（menu=目录, page=页面）" json:"menuType"`                  // 菜单类型（menu=目录, page=页面）
	Icon         *string    `gorm:"column:icon;comment:菜单图标" json:"icon"`                                                             // 菜单图标
	Path         *string    `gorm:"column:path;comment:路由路径" json:"path"`                                                             // 路由路径
	Component    *string    `gorm:"column:component;comment:前端组件路径（兼容vue-pure-admin）" json:"component"`                        // 前端组件路径（兼容vue-pure-admin）
	PermissionID *string    `gorm:"column:permission_id;comment:关联权限UUID（外键）" json:"permissionId"`                                 // 关联权限UUID（外键）
	SortOrder    int32      `gorm:"column:sort_order;not null;default:0;comment:排序序号（支持拖拽排序）" json:"sortOrder"`              // 排序序号（支持拖拽排序）
	Visible      int16      `gorm:"column:visible;not null;default:1;comment:是否可见（0=隐藏,1=显示）" json:"visible"`                  // 是否可见（0=隐藏,1=显示）
	Status       int16      `gorm:"column:status;not null;default:0;comment:菜单状态（0=启用,1=禁用）" json:"status"`                  // 菜单状态（0=启用,1=禁用）
	CreatedAt    time.Time  `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`             // 创建时间
	UpdatedAt    time.Time  `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`             // 更新时间
	DeletedAt    *time.Time `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                                  // 软删除时间（NULL=未删除）
}

// TableName MenuM's table name
func (*MenuM) TableName() string {
	return TableNameMenuM
}
