// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermissionM = "permission"

// PermissionM mapped from table <permission>
type PermissionM struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                       // 内部主键ID（自增序列）
	PermissionID   string     `gorm:"column:permission_id;not null;default:gen_random_uuid();comment:权限业务唯一UUID" json:"permissionId"` // 权限业务唯一UUID
	PermissionName string     `gorm:"column:permission_name;not null;comment:权限名称" json:"permissionName"`                             // 权限名称
	PermissionCode string     `gorm:"column:permission_code;not null;comment:权限编码（唯一标识）" json:"permissionCode"`                   // 权限编码（唯一标识）
	ResourceType   string     `gorm:"column:resource_type;not null;comment:资源类型（menu=菜单, button=按钮）" json:"resourceType"`        // 资源类型（menu=菜单, button=按钮）
	ResourcePath   *string    `gorm:"column:resource_path;comment:资源路径（如 /system/user/list）" json:"resourcePath"`                 // 资源路径（如 /system/user/list）
	Action         string     `gorm:"column:action;not null;comment:HTTP动词或自定义操作（GET/POST/export等）" json:"action"`            // HTTP动词或自定义操作（GET/POST/export等）
	Description    *string    `gorm:"column:description;comment:权限描述" json:"description"`                                           // 权限描述
	ParentID       *string    `gorm:"column:parent_id;comment:父权限UUID（用于构建权限树）" json:"parentId"`                                 // 父权限UUID（用于构建权限树）
	Path           *string    `gorm:"column:path;comment:全路径（用于树形查询优化）" json:"path"`                                             // 全路径（用于树形查询优化）
	Status         int16      `gorm:"column:status;not null;default:0;comment:权限状态（0=启用,1=禁用）" json:"status"`                  // 权限状态（0=启用,1=禁用）
	CreatedAt      time.Time  `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`           // 创建时间
	UpdatedAt      time.Time  `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`           // 更新时间
	DeletedAt      *time.Time `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                                  // 软删除时间（NULL=未删除）
}

// TableName PermissionM's table name
func (*PermissionM) TableName() string {
	return TableNamePermissionM
}
