// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoleM = "role"

// RoleM mapped from table <role>
type RoleM struct {
	ID          int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                          // 内部主键ID（自增序列）
	RoleID      string     `gorm:"column:role_id;not null;default:gen_random_uuid();comment:角色业务唯一UUID" json:"roleId"`         // 角色业务唯一UUID
	RoleName    string     `gorm:"column:role_name;not null;comment:角色名称" json:"roleName"`                                       // 角色名称
	RoleCode    string     `gorm:"column:role_code;not null;comment:角色编码（唯一标识，如super_admin、admin）" json:"roleCode"`     // 角色编码（唯一标识，如super_admin、admin）
	Description *string    `gorm:"column:description;comment:角色描述" json:"description"`                                          // 角色描述
	Status      int16      `gorm:"column:status;not null;default:0;comment:角色状态（0=启用,1=禁用）" json:"status"`                  // 角色状态（0=启用,1=禁用）
	SortOrder   int32      `gorm:"column:sort_order;not null;default:0;comment:排序序号" json:"sortOrder"`                           // 排序序号
	CreatedAt   time.Time  `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`         // 创建时间
	UpdatedAt   time.Time  `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`         // 更新时间
	DeletedAt   *time.Time `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                              // 软删除时间（NULL=未删除）
}

// TableName RoleM's table name
func (*RoleM) TableName() string {
	return TableNameRoleM
}
