// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserM = "user"

// UserM mapped from table <user>
type UserM struct {
	ID          int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`             // 内部主键ID（自增序列）
	UserID      string     `gorm:"column:user_id;not null;default:gen_random_uuid();comment:用户业务唯一UUID" json:"userId"` // 用户业务唯一UUID
	Username    string     `gorm:"column:username;not null;comment:用户名（唯一，登录用）" json:"username"`                       // 用户名（唯一，登录用）
	Password    string     `gorm:"column:password;not null;comment:密码哈希（bcrypt加密存储）" json:"password"`                  // 密码哈希（bcrypt加密存储）
	Email       *string    `gorm:"column:email;comment:电子邮箱（唯一）" json:"email"`                                         // 电子邮箱（唯一）
	Phone       *string    `gorm:"column:phone;comment:手机号（唯一）" json:"phone"`                                          // 手机号（唯一）
	Avatar      *string    `gorm:"column:avatar;comment:头像URL" json:"avatar"`                                          // 头像URL
	Nickname    string     `gorm:"column:nickname;not null;comment:用户昵称" json:"nickname"`                              // 用户昵称
	Gender      int16      `gorm:"column:gender;not null;comment:性别（0=未知,1=男,2=女）" json:"gender"`                      // 性别（0=未知,1=男,2=女）
	Status      int16      `gorm:"column:status;not null;comment:用户状态（0=活跃,1=禁用）" json:"status"`                       // 用户状态（0=活跃,1=禁用）
	LastLoginAt *time.Time `gorm:"column:last_login_at;comment:最后登录时间" json:"lastLoginAt"`                             // 最后登录时间
	CreatedAt   time.Time  `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt   time.Time  `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
	Description *string    `gorm:"column:description;comment:用户描述/简介" json:"description"`                              // 用户描述/简介
}

// TableName UserM's table name
func (*UserM) TableName() string {
	return TableNameUserM
}
