// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserConfigM = "user_config"

// UserConfigM mapped from table <user_config>
type UserConfigM struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`             // 内部主键ID（自增序列）
	UserID      string    `gorm:"column:user_id;not null;comment:用户UUID（外键）" json:"userId"`                           // 用户UUID（外键）
	ConfigKey   string    `gorm:"column:config_key;not null;comment:配置键名（唯一组合）" json:"configKey"`                     // 配置键名（唯一组合）
	ConfigValue string    `gorm:"column:config_value;not null;comment:配置值（JSONB格式）" json:"configValue"`               // 配置值（JSONB格式）
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"` // 更新时间
}

// TableName UserConfigM's table name
func (*UserConfigM) TableName() string {
	return TableNameUserConfigM
}
