// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRoleM = "user_role"

// UserRoleM mapped from table <user_role>
type UserRoleM struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                         // 内部主键ID（自增序列）
	UserID     string    `gorm:"column:user_id;not null;comment:用户UUID（外键）" json:"userId"`                                       // 用户UUID（外键）
	RoleID     string    `gorm:"column:role_id;not null;comment:角色UUID（外键）" json:"roleId"`                                       // 角色UUID（外键）
	AssignedAt time.Time `gorm:"column:assigned_at;not null;default:current_timestamp;comment:分配时间" json:"assignedAt"`         // 分配时间
}

// TableName UserRoleM's table name
func (*UserRoleM) TableName() string {
	return TableNameUserRoleM
}
