/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system-manage',
    path: '/system-manage',
    component: 'layout.base',
    meta: {
      title: 'system-manage',
      i18nKey: 'route.system-manage',
      icon: 'ph:gear-six',
      order: 2
    },
    children: [
      {
        name: 'system-manage_menu',
        path: '/system-manage/menu',
        component: 'view.system-manage_menu',
        meta: {
          title: 'system-manage_menu',
          i18nKey: 'route.system-manage_menu',
          icon: 'tabler:menu-4'
        }
      },
      {
        name: 'system-manage_permission',
        path: '/system-manage/permission',
        component: 'view.system-manage_permission',
        meta: {
          title: 'system-manage_permission',
          i18nKey: 'route.system-manage_permission',
          icon: 'mdi:shield-account-outline'
        }
      },
      {
        name: 'system-manage_role',
        path: '/system-manage/role',
        component: 'view.system-manage_role',
        meta: {
          title: 'system-manage_role',
          i18nKey: 'route.system-manage_role',
          icon: 'oui:app-users-roles'
        }
      },
      {
        name: 'system-manage_scheduled-task',
        path: '/system-manage/scheduled-task',
        component: 'view.system-manage_scheduled-task',
        meta: {
          title: 'system-manage_scheduled-task',
          i18nKey: 'route.system-manage_scheduled-task',
          icon: 'svg-spinners:clock'
        }
      },
      {
        name: 'system-manage_user',
        path: '/system-manage/user',
        component: 'view.system-manage_user',
        meta: {
          title: 'system-manage_user',
          i18nKey: 'route.system-manage_user',
          icon: 'ph:user-circle'
        }
      }
    ]
  }
];
