// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/clin211/gin-enterprise-template/internal/apiserver/biz"
	"github.com/clin211/gin-enterprise-template/internal/apiserver/pkg/validation"
	"github.com/clin211/gin-enterprise-template/internal/apiserver/store"
)

// Injectors from wire.go:

// NewServer 设置并创建包含所有必要依赖的 Web 服务器。
func NewServer(config *Config) (*Server, error) {
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(db)
	bizBiz := biz.NewBiz(datastore)
	validator := validation.New(datastore)
	userRetriever := &UserRetriever{
		store: datastore,
	}
	serverConfig := &ServerConfig{
		Config:    config,
		biz:       bizBiz,
		val:       validator,
		retriever: userRetriever,
	}
	server, err := NewWebServer(serverConfig)
	if err != nil {
		return nil, err
	}
	apiserverServer := &Server{
		cfg: serverConfig,
		srv: server,
	}
	return apiserverServer, nil
}
