// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Menu) Default() {
}

func (x *CreateMenuRequest) Default() {
	if x.SortOrder == nil {
		v := int32(0)
		x.SortOrder = &v
	}
}

func (x *CreateMenuResponse) Default() {
}

func (x *UpdateMenuRequest) Default() {
	if x.Visible == nil {
		v := int32(1)
		x.Visible = &v
	}
}

func (x *UpdateMenuResponse) Default() {
}

func (x *DeleteMenuRequest) Default() {
}

func (x *DeleteMenuResponse) Default() {
}

func (x *GetMenuRequest) Default() {
}

func (x *GetMenuResponse) Default() {
}

func (x *ListMenuRequest) Default() {
}

func (x *ListMenuResponse) Default() {
}

func (x *ListMenuTreeRequest) Default() {
}

func (x *ListMenuTreeResponse) Default() {
}

func (x *MenuTreeNode) Default() {
}

func (x *GetUserMenuTreeRequest) Default() {
}

func (x *GetUserMenuTreeResponse) Default() {
}
