// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: apiserver/v1/menu.proto

package v1

import (
	_ "github.com/onexstack/protoc-gen-defaults/defaults"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Menu 表示菜单信息
type Menu struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menuID 表示菜单 ID
	MenuID string `protobuf:"bytes,1,opt,name=menuID,proto3" json:"menuID,omitempty"`
	// parentID 表示父菜单 ID
	ParentID string `protobuf:"bytes,2,opt,name=parentID,proto3" json:"parentID,omitempty"`
	// menuName 表示菜单名称
	MenuName string `protobuf:"bytes,3,opt,name=menuName,proto3" json:"menuName,omitempty"`
	// menuCode 表示菜单编码
	MenuCode string `protobuf:"bytes,4,opt,name=menuCode,proto3" json:"menuCode,omitempty"`
	// menuType 表示菜单类型（menu=目录, page=页面）
	MenuType string `protobuf:"bytes,5,opt,name=menuType,proto3" json:"menuType,omitempty"`
	// icon 表示菜单图标
	Icon string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	// path 表示路由路径
	Path string `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	// component 表示前端组件路径
	Component string `protobuf:"bytes,8,opt,name=component,proto3" json:"component,omitempty"`
	// permissionID 表示关联权限 ID
	PermissionID string `protobuf:"bytes,9,opt,name=permissionID,proto3" json:"permissionID,omitempty"`
	// sortOrder 表示排序序号
	SortOrder int32 `protobuf:"varint,10,opt,name=sortOrder,proto3" json:"sortOrder,omitempty"`
	// visible 表示是否可见（0=隐藏,1=显示）
	Visible int32 `protobuf:"varint,11,opt,name=visible,proto3" json:"visible,omitempty"`
	// status 表示菜单状态（0=启用,1=禁用）
	Status int32 `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	// createdAt 表示创建时间
	CreatedAt int64 `protobuf:"varint,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     int64 `protobuf:"varint,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetMenuID() string {
	if x != nil {
		return x.MenuID
	}
	return ""
}

func (x *Menu) GetParentID() string {
	if x != nil {
		return x.ParentID
	}
	return ""
}

func (x *Menu) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *Menu) GetMenuCode() string {
	if x != nil {
		return x.MenuCode
	}
	return ""
}

func (x *Menu) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Menu) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Menu) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

func (x *Menu) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Menu) GetVisible() int32 {
	if x != nil {
		return x.Visible
	}
	return 0
}

func (x *Menu) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Menu) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Menu) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateMenuRequest 表示创建菜单请求
type CreateMenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parentID 表示父菜单 ID
	ParentID *string `protobuf:"bytes,1,opt,name=parentID,proto3,oneof" json:"parentID,omitempty"`
	// menuName 表示菜单名称
	MenuName string `protobuf:"bytes,2,opt,name=menuName,proto3" json:"menuName,omitempty"`
	// menuCode 表示菜单编码
	MenuCode string `protobuf:"bytes,3,opt,name=menuCode,proto3" json:"menuCode,omitempty"`
	// menuType 表示菜单类型（menu=目录, page=页面）
	MenuType string `protobuf:"bytes,4,opt,name=menuType,proto3" json:"menuType,omitempty"`
	// icon 表示菜单图标
	Icon *string `protobuf:"bytes,5,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// path 表示路由路径
	Path *string `protobuf:"bytes,6,opt,name=path,proto3,oneof" json:"path,omitempty"`
	// component 表示前端组件路径
	Component *string `protobuf:"bytes,7,opt,name=component,proto3,oneof" json:"component,omitempty"`
	// permissionID 表示关联权限 ID
	PermissionID *string `protobuf:"bytes,8,opt,name=permissionID,proto3,oneof" json:"permissionID,omitempty"`
	// sortOrder 表示排序序号
	SortOrder     *int32 `protobuf:"varint,9,opt,name=sortOrder,proto3,oneof" json:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMenuRequest) GetParentID() string {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return ""
}

func (x *CreateMenuRequest) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *CreateMenuRequest) GetMenuCode() string {
	if x != nil {
		return x.MenuCode
	}
	return ""
}

func (x *CreateMenuRequest) GetMenuType() string {
	if x != nil {
		return x.MenuType
	}
	return ""
}

func (x *CreateMenuRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *CreateMenuRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *CreateMenuRequest) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *CreateMenuRequest) GetPermissionID() string {
	if x != nil && x.PermissionID != nil {
		return *x.PermissionID
	}
	return ""
}

func (x *CreateMenuRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

// CreateMenuResponse 表示创建菜单响应
type CreateMenuResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menuID 表示新创建的菜单 ID
	MenuID        string `protobuf:"bytes,1,opt,name=menuID,proto3" json:"menuID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuResponse) Reset() {
	*x = CreateMenuResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuResponse) ProtoMessage() {}

func (x *CreateMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuResponse.ProtoReflect.Descriptor instead.
func (*CreateMenuResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuResponse) GetMenuID() string {
	if x != nil {
		return x.MenuID
	}
	return ""
}

// UpdateMenuRequest 表示更新菜单请求
type UpdateMenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menuID 表示菜单 ID
	// @gotags: uri:"menuID"
	MenuID string `protobuf:"bytes,1,opt,name=menuID,proto3" json:"menuID,omitempty" uri:"menuID"`
	// parentID 表示可选的父菜单 ID
	ParentID *string `protobuf:"bytes,2,opt,name=parentID,proto3,oneof" json:"parentID,omitempty"`
	// menuName 表示可选的菜单名称
	MenuName *string `protobuf:"bytes,3,opt,name=menuName,proto3,oneof" json:"menuName,omitempty"`
	// icon 表示可选的菜单图标
	Icon *string `protobuf:"bytes,4,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// path 表示可选的路由路径
	Path *string `protobuf:"bytes,5,opt,name=path,proto3,oneof" json:"path,omitempty"`
	// component 表示可选的前端组件路径
	Component *string `protobuf:"bytes,6,opt,name=component,proto3,oneof" json:"component,omitempty"`
	// sortOrder 表示可选的排序序号
	SortOrder *int32 `protobuf:"varint,7,opt,name=sortOrder,proto3,oneof" json:"sortOrder,omitempty"`
	// visible 表示可选的是否可见（0=隐藏,1=显示）
	Visible *int32 `protobuf:"varint,8,opt,name=visible,proto3,oneof" json:"visible,omitempty"`
	// status 表示可选的菜单状态（0=启用,1=禁用）
	Status        *int32 `protobuf:"varint,9,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMenuRequest) GetMenuID() string {
	if x != nil {
		return x.MenuID
	}
	return ""
}

func (x *UpdateMenuRequest) GetParentID() string {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return ""
}

func (x *UpdateMenuRequest) GetMenuName() string {
	if x != nil && x.MenuName != nil {
		return *x.MenuName
	}
	return ""
}

func (x *UpdateMenuRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateMenuRequest) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *UpdateMenuRequest) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *UpdateMenuRequest) GetSortOrder() int32 {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return 0
}

func (x *UpdateMenuRequest) GetVisible() int32 {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return 0
}

func (x *UpdateMenuRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// UpdateMenuResponse 表示更新菜单响应
type UpdateMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuResponse) Reset() {
	*x = UpdateMenuResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuResponse) ProtoMessage() {}

func (x *UpdateMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{4}
}

// DeleteMenuRequest 表示删除菜单请求
type DeleteMenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menuID 表示菜单 ID
	// @gotags: uri:"menuID"
	MenuID        string `protobuf:"bytes,1,opt,name=menuID,proto3" json:"menuID,omitempty" uri:"menuID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuRequest) Reset() {
	*x = DeleteMenuRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuRequest) ProtoMessage() {}

func (x *DeleteMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMenuRequest) GetMenuID() string {
	if x != nil {
		return x.MenuID
	}
	return ""
}

// DeleteMenuResponse 表示删除菜单响应
type DeleteMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuResponse) Reset() {
	*x = DeleteMenuResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuResponse) ProtoMessage() {}

func (x *DeleteMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{6}
}

// GetMenuRequest 表示获取菜单请求
type GetMenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menuID 表示菜单 ID
	// @gotags: uri:"menuID"
	MenuID        string `protobuf:"bytes,1,opt,name=menuID,proto3" json:"menuID,omitempty" uri:"menuID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{7}
}

func (x *GetMenuRequest) GetMenuID() string {
	if x != nil {
		return x.MenuID
	}
	return ""
}

// GetMenuResponse 表示获取菜单响应
type GetMenuResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menu 表示返回的菜单信息
	Menu          *Menu `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{8}
}

func (x *GetMenuResponse) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

// ListMenuRequest 表示菜单列表请求
type ListMenuRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pageToken 表示分页游标
	// @gotags: form:"page_token"
	PageToken string `protobuf:"bytes,1,opt,name=pageToken,proto3" json:"pageToken,omitempty" form:"page_token"`
	// pageSize 表示每页数量
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" form:"page_size"`
	// status 表示状态过滤（0=启用,1=禁用，留空表示全部）
	// @gotags: form:"status"
	Status *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	// menuType 表示菜单类型过滤（menu=目录, page=页面，留空表示全部）
	// @gotags: form:"menu_type"
	MenuType *string `protobuf:"bytes,4,opt,name=menuType,proto3,oneof" json:"menuType,omitempty" form:"menu_type"`
	// parentID 表示父菜单 ID 过滤
	// @gotags: form:"parent_id"
	ParentID      *string `protobuf:"bytes,5,opt,name=parentID,proto3,oneof" json:"parentID,omitempty" form:"parent_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuRequest) Reset() {
	*x = ListMenuRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuRequest) ProtoMessage() {}

func (x *ListMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuRequest.ProtoReflect.Descriptor instead.
func (*ListMenuRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{9}
}

func (x *ListMenuRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListMenuRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMenuRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListMenuRequest) GetMenuType() string {
	if x != nil && x.MenuType != nil {
		return *x.MenuType
	}
	return ""
}

func (x *ListMenuRequest) GetParentID() string {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return ""
}

// ListMenuResponse 表示菜单列表响应
type ListMenuResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示总菜单数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// menus 表示菜单列表
	Menus []*Menu `protobuf:"bytes,2,rep,name=menus,proto3" json:"menus,omitempty"`
	// pageToken 表示下一页游标
	PageToken     string `protobuf:"bytes,3,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuResponse) Reset() {
	*x = ListMenuResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuResponse) ProtoMessage() {}

func (x *ListMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuResponse.ProtoReflect.Descriptor instead.
func (*ListMenuResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{10}
}

func (x *ListMenuResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMenuResponse) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

func (x *ListMenuResponse) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListMenuTreeRequest 表示菜单树请求
type ListMenuTreeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 表示状态过滤（0=启用,1=禁用，留空表示全部）
	// @gotags: form:"status"
	Status        *int32 `protobuf:"varint,1,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuTreeRequest) Reset() {
	*x = ListMenuTreeRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuTreeRequest) ProtoMessage() {}

func (x *ListMenuTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuTreeRequest.ProtoReflect.Descriptor instead.
func (*ListMenuTreeRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{11}
}

func (x *ListMenuTreeRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// ListMenuTreeResponse 表示菜单树响应
type ListMenuTreeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menus 表示菜单树
	Menus         []*MenuTreeNode `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuTreeResponse) Reset() {
	*x = ListMenuTreeResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuTreeResponse) ProtoMessage() {}

func (x *ListMenuTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuTreeResponse.ProtoReflect.Descriptor instead.
func (*ListMenuTreeResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{12}
}

func (x *ListMenuTreeResponse) GetMenus() []*MenuTreeNode {
	if x != nil {
		return x.Menus
	}
	return nil
}

// MenuTreeNode 表示菜单树节点
type MenuTreeNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menu 表示菜单信息
	Menu *Menu `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	// children 表示子菜单列表
	Children      []*MenuTreeNode `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeNode) Reset() {
	*x = MenuTreeNode{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeNode) ProtoMessage() {}

func (x *MenuTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeNode.ProtoReflect.Descriptor instead.
func (*MenuTreeNode) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{13}
}

func (x *MenuTreeNode) GetMenu() *Menu {
	if x != nil {
		return x.Menu
	}
	return nil
}

func (x *MenuTreeNode) GetChildren() []*MenuTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

// GetUserMenuTreeRequest 表示获取用户菜单树请求
type GetUserMenuTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMenuTreeRequest) Reset() {
	*x = GetUserMenuTreeRequest{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMenuTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMenuTreeRequest) ProtoMessage() {}

func (x *GetUserMenuTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMenuTreeRequest.ProtoReflect.Descriptor instead.
func (*GetUserMenuTreeRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{14}
}

// GetUserMenuTreeResponse 表示获取用户菜单树响应
type GetUserMenuTreeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// menus 表示用户可见的菜单树
	Menus         []*MenuTreeNode `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMenuTreeResponse) Reset() {
	*x = GetUserMenuTreeResponse{}
	mi := &file_apiserver_v1_menu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMenuTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMenuTreeResponse) ProtoMessage() {}

func (x *GetUserMenuTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_menu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMenuTreeResponse.ProtoReflect.Descriptor instead.
func (*GetUserMenuTreeResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_menu_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserMenuTreeResponse) GetMenus() []*MenuTreeNode {
	if x != nil {
		return x.Menus
	}
	return nil
}

var File_apiserver_v1_menu_proto protoreflect.FileDescriptor

const file_apiserver_v1_menu_proto_rawDesc = "" +
	"\n" +
	"\x17apiserver/v1/menu.proto\x12\fapiserver.v1\x1a,github.com/onexstack/defaults/defaults.proto\"\x84\x03\n" +
	"\x04Menu\x12\x16\n" +
	"\x06menuID\x18\x01 \x01(\tR\x06menuID\x12\x1a\n" +
	"\bparentID\x18\x02 \x01(\tR\bparentID\x12\x1a\n" +
	"\bmenuName\x18\x03 \x01(\tR\bmenuName\x12\x1a\n" +
	"\bmenuCode\x18\x04 \x01(\tR\bmenuCode\x12\x1a\n" +
	"\bmenuType\x18\x05 \x01(\tR\bmenuType\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\b \x01(\tR\tcomponent\x12\"\n" +
	"\fpermissionID\x18\t \x01(\tR\fpermissionID\x12\x1c\n" +
	"\tsortOrder\x18\n" +
	" \x01(\x05R\tsortOrder\x12\x18\n" +
	"\avisible\x18\v \x01(\x05R\avisible\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\r \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0e \x01(\x03R\tupdatedAt\"\xfc\x02\n" +
	"\x11CreateMenuRequest\x12\x1f\n" +
	"\bparentID\x18\x01 \x01(\tH\x00R\bparentID\x88\x01\x01\x12\x1a\n" +
	"\bmenuName\x18\x02 \x01(\tR\bmenuName\x12\x1a\n" +
	"\bmenuCode\x18\x03 \x01(\tR\bmenuCode\x12\x1a\n" +
	"\bmenuType\x18\x04 \x01(\tR\bmenuType\x12\x17\n" +
	"\x04icon\x18\x05 \x01(\tH\x01R\x04icon\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x06 \x01(\tH\x02R\x04path\x88\x01\x01\x12!\n" +
	"\tcomponent\x18\a \x01(\tH\x03R\tcomponent\x88\x01\x01\x12'\n" +
	"\fpermissionID\x18\b \x01(\tH\x04R\fpermissionID\x88\x01\x01\x12(\n" +
	"\tsortOrder\x18\t \x01(\x05B\x05\x9aI\x02\x18\x00H\x05R\tsortOrder\x88\x01\x01B\v\n" +
	"\t_parentIDB\a\n" +
	"\x05_iconB\a\n" +
	"\x05_pathB\f\n" +
	"\n" +
	"_componentB\x0f\n" +
	"\r_permissionIDB\f\n" +
	"\n" +
	"_sortOrder\",\n" +
	"\x12CreateMenuResponse\x12\x16\n" +
	"\x06menuID\x18\x01 \x01(\tR\x06menuID\"\x87\x03\n" +
	"\x11UpdateMenuRequest\x12\x16\n" +
	"\x06menuID\x18\x01 \x01(\tR\x06menuID\x12\x1f\n" +
	"\bparentID\x18\x02 \x01(\tH\x00R\bparentID\x88\x01\x01\x12\x1f\n" +
	"\bmenuName\x18\x03 \x01(\tH\x01R\bmenuName\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x04 \x01(\tH\x02R\x04icon\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x05 \x01(\tH\x03R\x04path\x88\x01\x01\x12!\n" +
	"\tcomponent\x18\x06 \x01(\tH\x04R\tcomponent\x88\x01\x01\x12!\n" +
	"\tsortOrder\x18\a \x01(\x05H\x05R\tsortOrder\x88\x01\x01\x12$\n" +
	"\avisible\x18\b \x01(\x05B\x05\x9aI\x02\x18\x01H\x06R\avisible\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\t \x01(\x05H\aR\x06status\x88\x01\x01B\v\n" +
	"\t_parentIDB\v\n" +
	"\t_menuNameB\a\n" +
	"\x05_iconB\a\n" +
	"\x05_pathB\f\n" +
	"\n" +
	"_componentB\f\n" +
	"\n" +
	"_sortOrderB\n" +
	"\n" +
	"\b_visibleB\t\n" +
	"\a_status\"\x14\n" +
	"\x12UpdateMenuResponse\"+\n" +
	"\x11DeleteMenuRequest\x12\x16\n" +
	"\x06menuID\x18\x01 \x01(\tR\x06menuID\"\x14\n" +
	"\x12DeleteMenuResponse\"(\n" +
	"\x0eGetMenuRequest\x12\x16\n" +
	"\x06menuID\x18\x01 \x01(\tR\x06menuID\"9\n" +
	"\x0fGetMenuResponse\x12&\n" +
	"\x04menu\x18\x01 \x01(\v2\x12.apiserver.v1.MenuR\x04menu\"\xcf\x01\n" +
	"\x0fListMenuRequest\x12\x1c\n" +
	"\tpageToken\x18\x01 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x00R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bmenuType\x18\x04 \x01(\tH\x01R\bmenuType\x88\x01\x01\x12\x1f\n" +
	"\bparentID\x18\x05 \x01(\tH\x02R\bparentID\x88\x01\x01B\t\n" +
	"\a_statusB\v\n" +
	"\t_menuTypeB\v\n" +
	"\t_parentID\"z\n" +
	"\x10ListMenuResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12(\n" +
	"\x05menus\x18\x02 \x03(\v2\x12.apiserver.v1.MenuR\x05menus\x12\x1c\n" +
	"\tpageToken\x18\x03 \x01(\tR\tpageToken\"=\n" +
	"\x13ListMenuTreeRequest\x12\x1b\n" +
	"\x06status\x18\x01 \x01(\x05H\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"H\n" +
	"\x14ListMenuTreeResponse\x120\n" +
	"\x05menus\x18\x01 \x03(\v2\x1a.apiserver.v1.MenuTreeNodeR\x05menus\"n\n" +
	"\fMenuTreeNode\x12&\n" +
	"\x04menu\x18\x01 \x01(\v2\x12.apiserver.v1.MenuR\x04menu\x126\n" +
	"\bchildren\x18\x02 \x03(\v2\x1a.apiserver.v1.MenuTreeNodeR\bchildren\"\x18\n" +
	"\x16GetUserMenuTreeRequest\"K\n" +
	"\x17GetUserMenuTreeResponse\x120\n" +
	"\x05menus\x18\x01 \x03(\v2\x1a.apiserver.v1.MenuTreeNodeR\x05menusBDZBgithub.com/clin211/gin-enterprise-template/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_menu_proto_rawDescOnce sync.Once
	file_apiserver_v1_menu_proto_rawDescData []byte
)

func file_apiserver_v1_menu_proto_rawDescGZIP() []byte {
	file_apiserver_v1_menu_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_menu_proto_rawDesc), len(file_apiserver_v1_menu_proto_rawDesc)))
	})
	return file_apiserver_v1_menu_proto_rawDescData
}

var file_apiserver_v1_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apiserver_v1_menu_proto_goTypes = []any{
	(*Menu)(nil),                    // 0: apiserver.v1.Menu
	(*CreateMenuRequest)(nil),       // 1: apiserver.v1.CreateMenuRequest
	(*CreateMenuResponse)(nil),      // 2: apiserver.v1.CreateMenuResponse
	(*UpdateMenuRequest)(nil),       // 3: apiserver.v1.UpdateMenuRequest
	(*UpdateMenuResponse)(nil),      // 4: apiserver.v1.UpdateMenuResponse
	(*DeleteMenuRequest)(nil),       // 5: apiserver.v1.DeleteMenuRequest
	(*DeleteMenuResponse)(nil),      // 6: apiserver.v1.DeleteMenuResponse
	(*GetMenuRequest)(nil),          // 7: apiserver.v1.GetMenuRequest
	(*GetMenuResponse)(nil),         // 8: apiserver.v1.GetMenuResponse
	(*ListMenuRequest)(nil),         // 9: apiserver.v1.ListMenuRequest
	(*ListMenuResponse)(nil),        // 10: apiserver.v1.ListMenuResponse
	(*ListMenuTreeRequest)(nil),     // 11: apiserver.v1.ListMenuTreeRequest
	(*ListMenuTreeResponse)(nil),    // 12: apiserver.v1.ListMenuTreeResponse
	(*MenuTreeNode)(nil),            // 13: apiserver.v1.MenuTreeNode
	(*GetUserMenuTreeRequest)(nil),  // 14: apiserver.v1.GetUserMenuTreeRequest
	(*GetUserMenuTreeResponse)(nil), // 15: apiserver.v1.GetUserMenuTreeResponse
}
var file_apiserver_v1_menu_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.GetMenuResponse.menu:type_name -> apiserver.v1.Menu
	0,  // 1: apiserver.v1.ListMenuResponse.menus:type_name -> apiserver.v1.Menu
	13, // 2: apiserver.v1.ListMenuTreeResponse.menus:type_name -> apiserver.v1.MenuTreeNode
	0,  // 3: apiserver.v1.MenuTreeNode.menu:type_name -> apiserver.v1.Menu
	13, // 4: apiserver.v1.MenuTreeNode.children:type_name -> apiserver.v1.MenuTreeNode
	13, // 5: apiserver.v1.GetUserMenuTreeResponse.menus:type_name -> apiserver.v1.MenuTreeNode
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_apiserver_v1_menu_proto_init() }
func file_apiserver_v1_menu_proto_init() {
	if File_apiserver_v1_menu_proto != nil {
		return
	}
	file_apiserver_v1_menu_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_menu_proto_msgTypes[3].OneofWrappers = []any{}
	file_apiserver_v1_menu_proto_msgTypes[9].OneofWrappers = []any{}
	file_apiserver_v1_menu_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_menu_proto_rawDesc), len(file_apiserver_v1_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_menu_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_menu_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_menu_proto_msgTypes,
	}.Build()
	File_apiserver_v1_menu_proto = out.File
	file_apiserver_v1_menu_proto_goTypes = nil
	file_apiserver_v1_menu_proto_depIdxs = nil
}
