// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: apiserver/v1/permission.proto

package v1

import (
	_ "github.com/onexstack/protoc-gen-defaults/defaults"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission 表示权限信息
type Permission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionID 表示权限 ID
	PermissionID string `protobuf:"bytes,1,opt,name=permissionID,proto3" json:"permissionID,omitempty"`
	// permissionName 表示权限名称
	PermissionName string `protobuf:"bytes,2,opt,name=permissionName,proto3" json:"permissionName,omitempty"`
	// permissionCode 表示权限编码
	PermissionCode string `protobuf:"bytes,3,opt,name=permissionCode,proto3" json:"permissionCode,omitempty"`
	// resourceType 表示资源类型（menu=菜单, button=按钮）
	ResourceType string `protobuf:"bytes,4,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	// resourcePath 表示资源路径
	ResourcePath string `protobuf:"bytes,5,opt,name=resourcePath,proto3" json:"resourcePath,omitempty"`
	// action 表示操作（GET/POST 等）
	Action string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	// description 表示权限描述
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	// parentID 表示父权限 ID
	ParentID string `protobuf:"bytes,8,opt,name=parentID,proto3" json:"parentID,omitempty"`
	// path 表示全路径
	Path string `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	// status 表示权限状态（0=启用,1=禁用）
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	// createdAt 表示创建时间
	CreatedAt int64 `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示更新时间
	UpdatedAt     int64 `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

func (x *Permission) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *Permission) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *Permission) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Permission) GetResourcePath() string {
	if x != nil {
		return x.ResourcePath
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetParentID() string {
	if x != nil {
		return x.ParentID
	}
	return ""
}

func (x *Permission) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Permission) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Permission) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Permission) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreatePermissionRequest 表示创建权限请求
type CreatePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionName 表示权限名称
	PermissionName string `protobuf:"bytes,1,opt,name=permissionName,proto3" json:"permissionName,omitempty"`
	// permissionCode 表示权限编码
	PermissionCode string `protobuf:"bytes,2,opt,name=permissionCode,proto3" json:"permissionCode,omitempty"`
	// resourceType 表示资源类型（menu=菜单, button=按钮）
	ResourceType string `protobuf:"bytes,3,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	// resourcePath 表示资源路径
	ResourcePath *string `protobuf:"bytes,4,opt,name=resourcePath,proto3,oneof" json:"resourcePath,omitempty"`
	// action 表示操作（GET/POST 等）
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	// description 表示权限描述
	Description *string `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// parentID 表示父权限 ID
	ParentID      *string `protobuf:"bytes,7,opt,name=parentID,proto3,oneof" json:"parentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePermissionRequest) GetPermissionName() string {
	if x != nil {
		return x.PermissionName
	}
	return ""
}

func (x *CreatePermissionRequest) GetPermissionCode() string {
	if x != nil {
		return x.PermissionCode
	}
	return ""
}

func (x *CreatePermissionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CreatePermissionRequest) GetResourcePath() string {
	if x != nil && x.ResourcePath != nil {
		return *x.ResourcePath
	}
	return ""
}

func (x *CreatePermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePermissionRequest) GetParentID() string {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return ""
}

// CreatePermissionResponse 表示创建权限响应
type CreatePermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionID 表示新创建的权限 ID
	PermissionID  string `protobuf:"bytes,1,opt,name=permissionID,proto3" json:"permissionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePermissionResponse) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

// UpdatePermissionRequest 表示更新权限请求
type UpdatePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionID 表示权限 ID
	// @gotags: uri:"permissionID"
	PermissionID string `protobuf:"bytes,1,opt,name=permissionID,proto3" json:"permissionID,omitempty" uri:"permissionID"`
	// permissionName 表示可选的权限名称
	PermissionName *string `protobuf:"bytes,2,opt,name=permissionName,proto3,oneof" json:"permissionName,omitempty"`
	// description 表示可选的权限描述
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// status 表示可选的权限状态（0=启用,1=禁用）
	Status        *int32 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePermissionRequest) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

func (x *UpdatePermissionRequest) GetPermissionName() string {
	if x != nil && x.PermissionName != nil {
		return *x.PermissionName
	}
	return ""
}

func (x *UpdatePermissionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePermissionRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// UpdatePermissionResponse 表示更新权限响应
type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{4}
}

// DeletePermissionRequest 表示删除权限请求
type DeletePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionID 表示权限 ID
	// @gotags: uri:"permissionID"
	PermissionID  string `protobuf:"bytes,1,opt,name=permissionID,proto3" json:"permissionID,omitempty" uri:"permissionID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePermissionRequest) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

// DeletePermissionResponse 表示删除权限响应
type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{6}
}

// GetPermissionRequest 表示获取权限请求
type GetPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissionID 表示权限 ID
	// @gotags: uri:"permissionID"
	PermissionID  string `protobuf:"bytes,1,opt,name=permissionID,proto3" json:"permissionID,omitempty" uri:"permissionID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{7}
}

func (x *GetPermissionRequest) GetPermissionID() string {
	if x != nil {
		return x.PermissionID
	}
	return ""
}

// GetPermissionResponse 表示获取权限响应
type GetPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission 表示返回的权限信息
	Permission    *Permission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponse) Reset() {
	*x = GetPermissionResponse{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponse) ProtoMessage() {}

func (x *GetPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{8}
}

func (x *GetPermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

// ListPermissionRequest 表示权限列表请求
type ListPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pageToken 表示分页游标
	// @gotags: form:"page_token"
	PageToken string `protobuf:"bytes,1,opt,name=pageToken,proto3" json:"pageToken,omitempty" form:"page_token"`
	// pageSize 表示每页数量
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" form:"page_size"`
	// resourceType 表示资源类型过滤（menu=菜单, button=按钮，留空表示全部）
	// @gotags: form:"resource_type"
	ResourceType *string `protobuf:"bytes,3,opt,name=resourceType,proto3,oneof" json:"resourceType,omitempty" form:"resource_type"`
	// status 表示状态过滤（0=启用,1=禁用，留空表示全部）
	// @gotags: form:"status"
	Status *int32 `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	// parentID 表示父权限 ID 过滤
	// @gotags: form:"parent_id"
	ParentID      *string `protobuf:"bytes,5,opt,name=parentID,proto3,oneof" json:"parentID,omitempty" form:"parent_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionRequest) Reset() {
	*x = ListPermissionRequest{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionRequest) ProtoMessage() {}

func (x *ListPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{9}
}

func (x *ListPermissionRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPermissionRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermissionRequest) GetResourceType() string {
	if x != nil && x.ResourceType != nil {
		return *x.ResourceType
	}
	return ""
}

func (x *ListPermissionRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListPermissionRequest) GetParentID() string {
	if x != nil && x.ParentID != nil {
		return *x.ParentID
	}
	return ""
}

// ListPermissionResponse 表示权限列表响应
type ListPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示总权限数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// permissions 表示权限列表
	Permissions []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// pageToken 表示下一页游标
	PageToken     string `protobuf:"bytes,3,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionResponse) Reset() {
	*x = ListPermissionResponse{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionResponse) ProtoMessage() {}

func (x *ListPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{10}
}

func (x *ListPermissionResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPermissionResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListPermissionResponse) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListPermissionTreeRequest 表示权限树请求
type ListPermissionTreeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level 表示层级深度（0=全部，1=仅根节点，2=两级，以此类推）
	// @gotags: form:"level"
	Level *int32 `protobuf:"varint,1,opt,name=level,proto3,oneof" json:"level,omitempty" form:"level"`
	// resourceType 表示资源类型过滤
	// @gotags: form:"resource_type"
	ResourceType *string `protobuf:"bytes,2,opt,name=resourceType,proto3,oneof" json:"resourceType,omitempty" form:"resource_type"`
	// status 表示状态过滤
	// @gotags: form:"status"
	Status        *int32 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionTreeRequest) Reset() {
	*x = ListPermissionTreeRequest{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionTreeRequest) ProtoMessage() {}

func (x *ListPermissionTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionTreeRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionTreeRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{11}
}

func (x *ListPermissionTreeRequest) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *ListPermissionTreeRequest) GetResourceType() string {
	if x != nil && x.ResourceType != nil {
		return *x.ResourceType
	}
	return ""
}

func (x *ListPermissionTreeRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

// ListPermissionTreeResponse 表示权限树响应
type ListPermissionTreeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissions 表示权限树
	Permissions   []*PermissionTreeNode `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionTreeResponse) Reset() {
	*x = ListPermissionTreeResponse{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionTreeResponse) ProtoMessage() {}

func (x *ListPermissionTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionTreeResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionTreeResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{12}
}

func (x *ListPermissionTreeResponse) GetPermissions() []*PermissionTreeNode {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// PermissionTreeNode 表示权限树节点
type PermissionTreeNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission 表示权限信息
	Permission *Permission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	// children 表示子权限列表
	Children      []*PermissionTreeNode `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionTreeNode) Reset() {
	*x = PermissionTreeNode{}
	mi := &file_apiserver_v1_permission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionTreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionTreeNode) ProtoMessage() {}

func (x *PermissionTreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_permission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionTreeNode.ProtoReflect.Descriptor instead.
func (*PermissionTreeNode) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_permission_proto_rawDescGZIP(), []int{13}
}

func (x *PermissionTreeNode) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *PermissionTreeNode) GetChildren() []*PermissionTreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_apiserver_v1_permission_proto protoreflect.FileDescriptor

const file_apiserver_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\x1dapiserver/v1/permission.proto\x12\fapiserver.v1\x1a,github.com/onexstack/defaults/defaults.proto\"\x86\x03\n" +
	"\n" +
	"Permission\x12\"\n" +
	"\fpermissionID\x18\x01 \x01(\tR\fpermissionID\x12&\n" +
	"\x0epermissionName\x18\x02 \x01(\tR\x0epermissionName\x12&\n" +
	"\x0epermissionCode\x18\x03 \x01(\tR\x0epermissionCode\x12\"\n" +
	"\fresourceType\x18\x04 \x01(\tR\fresourceType\x12\"\n" +
	"\fresourcePath\x18\x05 \x01(\tR\fresourcePath\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\bparentID\x18\b \x01(\tR\bparentID\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\x03R\tupdatedAt\"\xc4\x02\n" +
	"\x17CreatePermissionRequest\x12&\n" +
	"\x0epermissionName\x18\x01 \x01(\tR\x0epermissionName\x12&\n" +
	"\x0epermissionCode\x18\x02 \x01(\tR\x0epermissionCode\x12\"\n" +
	"\fresourceType\x18\x03 \x01(\tR\fresourceType\x12'\n" +
	"\fresourcePath\x18\x04 \x01(\tH\x00R\fresourcePath\x88\x01\x01\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bparentID\x18\a \x01(\tH\x02R\bparentID\x88\x01\x01B\x0f\n" +
	"\r_resourcePathB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_parentID\">\n" +
	"\x18CreatePermissionResponse\x12\"\n" +
	"\fpermissionID\x18\x01 \x01(\tR\fpermissionID\"\xdc\x01\n" +
	"\x17UpdatePermissionRequest\x12\"\n" +
	"\fpermissionID\x18\x01 \x01(\tR\fpermissionID\x12+\n" +
	"\x0epermissionName\x18\x02 \x01(\tH\x00R\x0epermissionName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x05H\x02R\x06status\x88\x01\x01B\x11\n" +
	"\x0f_permissionNameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"\x1a\n" +
	"\x18UpdatePermissionResponse\"=\n" +
	"\x17DeletePermissionRequest\x12\"\n" +
	"\fpermissionID\x18\x01 \x01(\tR\fpermissionID\"\x1a\n" +
	"\x18DeletePermissionResponse\":\n" +
	"\x14GetPermissionRequest\x12\"\n" +
	"\fpermissionID\x18\x01 \x01(\tR\fpermissionID\"Q\n" +
	"\x15GetPermissionResponse\x128\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x18.apiserver.v1.PermissionR\n" +
	"permission\"\xe1\x01\n" +
	"\x15ListPermissionRequest\x12\x1c\n" +
	"\tpageToken\x18\x01 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12'\n" +
	"\fresourceType\x18\x03 \x01(\tH\x00R\fresourceType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\x05H\x01R\x06status\x88\x01\x01\x12\x1f\n" +
	"\bparentID\x18\x05 \x01(\tH\x02R\bparentID\x88\x01\x01B\x0f\n" +
	"\r_resourceTypeB\t\n" +
	"\a_statusB\v\n" +
	"\t_parentID\"\x92\x01\n" +
	"\x16ListPermissionResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12:\n" +
	"\vpermissions\x18\x02 \x03(\v2\x18.apiserver.v1.PermissionR\vpermissions\x12\x1c\n" +
	"\tpageToken\x18\x03 \x01(\tR\tpageToken\"\xa9\x01\n" +
	"\x19ListPermissionTreeRequest\x12 \n" +
	"\x05level\x18\x01 \x01(\x05B\x05\x9aI\x02\x18\x00H\x00R\x05level\x88\x01\x01\x12'\n" +
	"\fresourceType\x18\x02 \x01(\tH\x01R\fresourceType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x02R\x06status\x88\x01\x01B\b\n" +
	"\x06_levelB\x0f\n" +
	"\r_resourceTypeB\t\n" +
	"\a_status\"`\n" +
	"\x1aListPermissionTreeResponse\x12B\n" +
	"\vpermissions\x18\x01 \x03(\v2 .apiserver.v1.PermissionTreeNodeR\vpermissions\"\x8c\x01\n" +
	"\x12PermissionTreeNode\x128\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x18.apiserver.v1.PermissionR\n" +
	"permission\x12<\n" +
	"\bchildren\x18\x02 \x03(\v2 .apiserver.v1.PermissionTreeNodeR\bchildrenBDZBgithub.com/clin211/gin-enterprise-template/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_permission_proto_rawDescOnce sync.Once
	file_apiserver_v1_permission_proto_rawDescData []byte
)

func file_apiserver_v1_permission_proto_rawDescGZIP() []byte {
	file_apiserver_v1_permission_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_permission_proto_rawDesc), len(file_apiserver_v1_permission_proto_rawDesc)))
	})
	return file_apiserver_v1_permission_proto_rawDescData
}

var file_apiserver_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_apiserver_v1_permission_proto_goTypes = []any{
	(*Permission)(nil),                 // 0: apiserver.v1.Permission
	(*CreatePermissionRequest)(nil),    // 1: apiserver.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),   // 2: apiserver.v1.CreatePermissionResponse
	(*UpdatePermissionRequest)(nil),    // 3: apiserver.v1.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil),   // 4: apiserver.v1.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),    // 5: apiserver.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),   // 6: apiserver.v1.DeletePermissionResponse
	(*GetPermissionRequest)(nil),       // 7: apiserver.v1.GetPermissionRequest
	(*GetPermissionResponse)(nil),      // 8: apiserver.v1.GetPermissionResponse
	(*ListPermissionRequest)(nil),      // 9: apiserver.v1.ListPermissionRequest
	(*ListPermissionResponse)(nil),     // 10: apiserver.v1.ListPermissionResponse
	(*ListPermissionTreeRequest)(nil),  // 11: apiserver.v1.ListPermissionTreeRequest
	(*ListPermissionTreeResponse)(nil), // 12: apiserver.v1.ListPermissionTreeResponse
	(*PermissionTreeNode)(nil),         // 13: apiserver.v1.PermissionTreeNode
}
var file_apiserver_v1_permission_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.GetPermissionResponse.permission:type_name -> apiserver.v1.Permission
	0,  // 1: apiserver.v1.ListPermissionResponse.permissions:type_name -> apiserver.v1.Permission
	13, // 2: apiserver.v1.ListPermissionTreeResponse.permissions:type_name -> apiserver.v1.PermissionTreeNode
	0,  // 3: apiserver.v1.PermissionTreeNode.permission:type_name -> apiserver.v1.Permission
	13, // 4: apiserver.v1.PermissionTreeNode.children:type_name -> apiserver.v1.PermissionTreeNode
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_apiserver_v1_permission_proto_init() }
func file_apiserver_v1_permission_proto_init() {
	if File_apiserver_v1_permission_proto != nil {
		return
	}
	file_apiserver_v1_permission_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_permission_proto_msgTypes[3].OneofWrappers = []any{}
	file_apiserver_v1_permission_proto_msgTypes[9].OneofWrappers = []any{}
	file_apiserver_v1_permission_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_permission_proto_rawDesc), len(file_apiserver_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_permission_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_permission_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_permission_proto_msgTypes,
	}.Build()
	File_apiserver_v1_permission_proto = out.File
	file_apiserver_v1_permission_proto_goTypes = nil
	file_apiserver_v1_permission_proto_depIdxs = nil
}
