// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermissionM = "role_permission"

// RolePermissionM mapped from table <role_permission>
type RolePermissionM struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                     // 内部主键ID（自增序列）
	RoleID       string    `gorm:"column:role_id;not null;comment:角色UUID（外键）" json:"roleId"`                                       // 角色UUID（外键）
	PermissionID string    `gorm:"column:permission_id;not null;comment:权限UUID（外键）" json:"permissionId"`                           // 权限UUID（外键）
	Version      int32     `gorm:"column:version;not null;default:1;comment:乐观锁版本号" json:"version"`                                // 乐观锁版本号
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`             // 创建时间
}

// TableName RolePermissionM's table name
func (*RolePermissionM) TableName() string {
	return TableNameRolePermissionM
}
