// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCasbinRuleM = "casbin_rule"

// CasbinRuleM mapped from table <casbin_rule>
type CasbinRuleM struct {
	ID    int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"` // 内部主键ID（自增序列）
	Ptype *string `gorm:"column:ptype;comment:规则类型（p=权限, g=角色继承）" json:"ptype"`                   // 规则类型（p=权限, g=角色继承）
	V0    *string `gorm:"column:v0;comment:主体（用户/角色）" json:"v0"`                                  // 主体（用户/角色）
	V1    *string `gorm:"column:v1;comment:资源（对象）" json:"v1"`                                     // 资源（对象）
	V2    *string `gorm:"column:v2;comment:动作（读/写等）" json:"v2"`                                   // 动作（读/写等）
	V3    *string `gorm:"column:v3;comment:扩展字段1（条件等）" json:"v3"`                                 // 扩展字段1（条件等）
	V4    *string `gorm:"column:v4;comment:扩展字段2" json:"v4"`                                      // 扩展字段2
	V5    *string `gorm:"column:v5;comment:扩展字段3" json:"v5"`                                      // 扩展字段3
}

// TableName CasbinRuleM's table name
func (*CasbinRuleM) TableName() string {
	return TableNameCasbinRuleM
}
