// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameScheduledTaskM = "scheduled_task"

// ScheduledTaskM mapped from table <scheduled_task>
type ScheduledTaskM struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                                  // 内部主键ID（自增序列）
	ScheduledTaskID string         `gorm:"column:scheduled_task_id;not null;default:gen_random_uuid();comment:定时任务业务唯一UUID" json:"scheduledTaskId"` // 定时任务业务唯一UUID
	Name            string         `gorm:"column:name;not null;comment:任务名称" json:"name"`                                                           // 任务名称
	TaskType        string         `gorm:"column:task_type;not null;comment:任务类型（对应 worker 注册的 TaskType）" json:"taskType"`                          // 任务类型（对应 worker 注册的 TaskType）
	Payload         string         `gorm:"column:payload;not null;default:{};comment:任务载荷（JSONB格式，传递给 worker 的参数）" json:"payload"`                  // 任务载荷（JSONB格式，传递给 worker 的参数）
	CronExpr        string         `gorm:"column:cron_expr;not null;comment:Cron 表达式（如 0 9 * * *）" json:"cronExpr"`                                 // Cron 表达式（如 0 9 * * *）
	Queue           string         `gorm:"column:queue;not null;comment:Asynq 队列名称" json:"queue"`                                                   // Asynq 队列名称
	Enabled         bool           `gorm:"column:enabled;not null;default:true;comment:是否启用（true=启用, false=暂停）" json:"enabled"`                     // 是否启用（true=启用, false=暂停）
	Timezone        string         `gorm:"column:timezone;not null;comment:Cron 表达式时区（如 Asia/Shanghai）" json:"timezone"`                            // Cron 表达式时区（如 Asia/Shanghai）
	UserID          string         `gorm:"column:user_id;not null;comment:创建者用户UUID" json:"userId"`                                                 // 创建者用户UUID
	NextRunTime     *time.Time     `gorm:"column:next_run_time;comment:下次执行时间（由调度器计算）" json:"nextRunTime"`                                          // 下次执行时间（由调度器计算）
	LastScheduledAt *time.Time     `gorm:"column:last_scheduled_at;comment:最近一次调度时间" json:"lastScheduledAt"`                                        // 最近一次调度时间
	LastExecutionID *string        `gorm:"column:last_execution_id;comment:最近一次执行记录UUID" json:"lastExecutionId"`                                    // 最近一次执行记录UUID
	LastError       *string        `gorm:"column:last_error;comment:最近一次执行错误信息" json:"lastError"`                                                   // 最近一次执行错误信息
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`                      // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`                      // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:软删除时间（NULL=未删除）" json:"deletedAt"`                                              // 软删除时间（NULL=未删除）
}

// TableName ScheduledTaskM's table name
func (*ScheduledTaskM) TableName() string {
	return TableNameScheduledTaskM
}
