// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScheduledTaskExecutionM = "scheduled_task_execution"

// ScheduledTaskExecutionM mapped from table <scheduled_task_execution>
type ScheduledTaskExecutionM struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:内部主键ID（自增序列）" json:"id"`                                              // 内部主键ID（自增序列）
	ExecutionID     string     `gorm:"column:execution_id;not null;default:gen_random_uuid();comment:执行记录业务唯一UUID" json:"executionId"`                      // 执行记录业务唯一UUID
	ScheduledTaskID string     `gorm:"column:scheduled_task_id;not null;comment:关联的定时任务UUID" json:"scheduledTaskId"`                                        // 关联的定时任务UUID
	UserID          string     `gorm:"column:user_id;not null;comment:创建者用户UUID" json:"userId"`                                                             // 创建者用户UUID
	TriggerType     string     `gorm:"column:trigger_type;not null;comment:触发类型（scheduled=定时触发, manual=手动触发）" json:"triggerType"`                           // 触发类型（scheduled=定时触发, manual=手动触发）
	ScheduledAt     time.Time  `gorm:"column:scheduled_at;not null;comment:计划执行时间" json:"scheduledAt"`                                                      // 计划执行时间
	EnqueuedAt      *time.Time `gorm:"column:enqueued_at;comment:任务入队时间" json:"enqueuedAt"`                                                                 // 任务入队时间
	AsynqTaskID     *string    `gorm:"column:asynq_task_id;comment:Asynq 内部任务ID" json:"asynqTaskId"`                                                        // Asynq 内部任务ID
	DispatchStatus  string     `gorm:"column:dispatch_status;not null;comment:调度状态（pending=enqueued=入队成功, failed=入队失败）" json:"dispatchStatus"`              // 调度状态（pending=enqueued=入队成功, failed=入队失败）
	ProcessStatus   string     `gorm:"column:process_status;not null;comment:处理状态（pending=待处理, running=执行中, completed=成功, failed=失败）" json:"processStatus"` // 处理状态（pending=待处理, running=执行中, completed=成功, failed=失败）
	Attempt         int32      `gorm:"column:attempt;not null;comment:执行重试次数" json:"attempt"`                                                               // 执行重试次数
	ErrorMsg        *string    `gorm:"column:error_msg;comment:执行错误信息" json:"errorMsg"`                                                                     // 执行错误信息
	StartedAt       *time.Time `gorm:"column:started_at;comment:开始执行时间" json:"startedAt"`                                                                   // 开始执行时间
	FinishedAt      *time.Time `gorm:"column:finished_at;comment:执行完成时间" json:"finishedAt"`                                                                 // 执行完成时间
	DurationMs      int64      `gorm:"column:duration_ms;not null;comment:执行耗时（毫秒）" json:"durationMs"`                                                      // 执行耗时（毫秒）
	CreatedAt       time.Time  `gorm:"column:created_at;not null;default:current_timestamp;comment:创建时间" json:"createdAt"`                                  // 创建时间
	UpdatedAt       time.Time  `gorm:"column:updated_at;not null;default:current_timestamp;comment:更新时间" json:"updatedAt"`                                  // 更新时间
}

// TableName ScheduledTaskExecutionM's table name
func (*ScheduledTaskExecutionM) TableName() string {
	return TableNameScheduledTaskExecutionM
}
