// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: apiserver/v1/apiserver.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apiserver_v1_apiserver_proto protoreflect.FileDescriptor

const file_apiserver_v1_apiserver_proto_rawDesc = "" +
	"\n" +
	"\x1capiserver/v1/apiserver.proto\x12\fapiserver.v1\x1a\x1aapiserver/v1/healthz.proto\x1a\x17apiserver/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xa6\f\n" +
	"\tAPIServer\x12\x91\x01\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x1d.apiserver.v1.HealthzResponse\"O\x92A<\n" +
	"\f服务治理\x12\f健康检查\x1a\x1e检查服务是否健康运行\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12\xac\x01\n" +
	"\x05Login\x12\x1a.apiserver.v1.LoginRequest\x1a\x1b.apiserver.v1.LoginResponse\"j\x92AN\n" +
	"\f用户认证\x12\f用户登录\x1a0用户使用用户名和密码进行登录认证\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12\xc2\x01\n" +
	"\fRefreshToken\x12!.apiserver.v1.RefreshTokenRequest\x1a\x1b.apiserver.v1.LoginResponse\"r\x92AN\n" +
	"\f用户认证\x12\f刷新令牌\x1a0使用现有令牌刷新获取新的访问令牌\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/auth/refresh-token\x12\x9e\x01\n" +
	"\n" +
	"CreateUser\x12\x1f.apiserver.v1.CreateUserRequest\x1a .apiserver.v1.CreateUserResponse\"M\x92A6\n" +
	"\f用户管理\x12\f创建用户\x1a\x18创建一个新的用户\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12\xa5\x01\n" +
	"\aGetUser\x12\x1c.apiserver.v1.GetUserRequest\x1a\x1d.apiserver.v1.GetUserResponse\"]\x92A@\n" +
	"\f用户管理\x12\f获取用户\x1a\"根据用户 ID 获取用户信息\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/users/{userID}\x12\xb1\x01\n" +
	"\n" +
	"UpdateUser\x12\x1f.apiserver.v1.UpdateUserRequest\x1a .apiserver.v1.UpdateUserResponse\"`\x92A@\n" +
	"\f用户管理\x12\f更新用户\x1a\"根据用户 ID 更新用户信息\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/users/{userID}\x12\xa8\x01\n" +
	"\n" +
	"DeleteUser\x12\x1f.apiserver.v1.DeleteUserRequest\x1a .apiserver.v1.DeleteUserResponse\"W\x92A:\n" +
	"\f用户管理\x12\f删除用户\x1a\x1c根据用户 ID 删除用户\x82\xd3\xe4\x93\x02\x14*\x12/v1/users/{userID}\x12\x99\x01\n" +
	"\tListUsers\x12\x1d.apiserver.v1.ListUserRequest\x1a\x1e.apiserver.v1.ListUserResponse\"M\x92A9\n" +
	"\f用户管理\x12\f列表用户\x1a\x1b获取所有用户的列表\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\xcc\x01\n" +
	"\x0eChangePassword\x12#.apiserver.v1.ChangePasswordRequest\x1a$.apiserver.v1.ChangePasswordResponse\"o\x92A?\n" +
	"\f用户管理\x12\f修改密码\x1a!当前用户修改自己的密码\x82\xd3\xe4\x93\x02':\x01*\x1a\"/v1/users/{userID}/change-passwordB\x90\x03\x92A\xc8\x02\x12\x9d\x02\n" +
	"\rAPI Server v1\x12\x98\x01基于 gin-enterprise-template 的通用后端 API 服务：\n" +
	"- JWT 用户认证\n" +
	"- 用户基础管理\n" +
	"- RESTful 资源接口\n" +
	"- OpenTelemetry 可观测性\"l\n" +
	"\x1egin-enterprise-template 项目\x122https://github.com/clin211/gin-enterprise-template\x1a\x16767425412lin@gmail.com2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZBgithub.com/clin211/gin-enterprise-template/pkg/api/apiserver/v1;v1b\x06proto3"

var file_apiserver_v1_apiserver_proto_goTypes = []any{
	(*emptypb.Empty)(nil),          // 0: google.protobuf.Empty
	(*LoginRequest)(nil),           // 1: apiserver.v1.LoginRequest
	(*RefreshTokenRequest)(nil),    // 2: apiserver.v1.RefreshTokenRequest
	(*CreateUserRequest)(nil),      // 3: apiserver.v1.CreateUserRequest
	(*GetUserRequest)(nil),         // 4: apiserver.v1.GetUserRequest
	(*UpdateUserRequest)(nil),      // 5: apiserver.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),      // 6: apiserver.v1.DeleteUserRequest
	(*ListUserRequest)(nil),        // 7: apiserver.v1.ListUserRequest
	(*ChangePasswordRequest)(nil),  // 8: apiserver.v1.ChangePasswordRequest
	(*HealthzResponse)(nil),        // 9: apiserver.v1.HealthzResponse
	(*LoginResponse)(nil),          // 10: apiserver.v1.LoginResponse
	(*CreateUserResponse)(nil),     // 11: apiserver.v1.CreateUserResponse
	(*GetUserResponse)(nil),        // 12: apiserver.v1.GetUserResponse
	(*UpdateUserResponse)(nil),     // 13: apiserver.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),     // 14: apiserver.v1.DeleteUserResponse
	(*ListUserResponse)(nil),       // 15: apiserver.v1.ListUserResponse
	(*ChangePasswordResponse)(nil), // 16: apiserver.v1.ChangePasswordResponse
}
var file_apiserver_v1_apiserver_proto_depIdxs = []int32{
	0,  // 0: apiserver.v1.APIServer.Healthz:input_type -> google.protobuf.Empty
	1,  // 1: apiserver.v1.APIServer.Login:input_type -> apiserver.v1.LoginRequest
	2,  // 2: apiserver.v1.APIServer.RefreshToken:input_type -> apiserver.v1.RefreshTokenRequest
	3,  // 3: apiserver.v1.APIServer.CreateUser:input_type -> apiserver.v1.CreateUserRequest
	4,  // 4: apiserver.v1.APIServer.GetUser:input_type -> apiserver.v1.GetUserRequest
	5,  // 5: apiserver.v1.APIServer.UpdateUser:input_type -> apiserver.v1.UpdateUserRequest
	6,  // 6: apiserver.v1.APIServer.DeleteUser:input_type -> apiserver.v1.DeleteUserRequest
	7,  // 7: apiserver.v1.APIServer.ListUsers:input_type -> apiserver.v1.ListUserRequest
	8,  // 8: apiserver.v1.APIServer.ChangePassword:input_type -> apiserver.v1.ChangePasswordRequest
	9,  // 9: apiserver.v1.APIServer.Healthz:output_type -> apiserver.v1.HealthzResponse
	10, // 10: apiserver.v1.APIServer.Login:output_type -> apiserver.v1.LoginResponse
	10, // 11: apiserver.v1.APIServer.RefreshToken:output_type -> apiserver.v1.LoginResponse
	11, // 12: apiserver.v1.APIServer.CreateUser:output_type -> apiserver.v1.CreateUserResponse
	12, // 13: apiserver.v1.APIServer.GetUser:output_type -> apiserver.v1.GetUserResponse
	13, // 14: apiserver.v1.APIServer.UpdateUser:output_type -> apiserver.v1.UpdateUserResponse
	14, // 15: apiserver.v1.APIServer.DeleteUser:output_type -> apiserver.v1.DeleteUserResponse
	15, // 16: apiserver.v1.APIServer.ListUsers:output_type -> apiserver.v1.ListUserResponse
	16, // 17: apiserver.v1.APIServer.ChangePassword:output_type -> apiserver.v1.ChangePasswordResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_apiserver_proto_init() }
func file_apiserver_v1_apiserver_proto_init() {
	if File_apiserver_v1_apiserver_proto != nil {
		return
	}
	file_apiserver_v1_healthz_proto_init()
	file_apiserver_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_apiserver_proto_rawDesc), len(file_apiserver_v1_apiserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiserver_v1_apiserver_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_apiserver_proto_depIdxs,
	}.Build()
	File_apiserver_v1_apiserver_proto = out.File
	file_apiserver_v1_apiserver_proto_goTypes = nil
	file_apiserver_v1_apiserver_proto_depIdxs = nil
}
