// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Role) Default() {
}

func (x *CreateRoleRequest) Default() {
	if x.SortOrder == nil {
		v := int32(0)
		x.SortOrder = &v
	}
}

func (x *CreateRoleResponse) Default() {
}

func (x *UpdateRoleRequest) Default() {
}

func (x *UpdateRoleResponse) Default() {
}

func (x *DeleteRoleRequest) Default() {
}

func (x *DeleteRoleResponse) Default() {
}

func (x *GetRoleRequest) Default() {
}

func (x *GetRoleResponse) Default() {
}

func (x *ListRoleRequest) Default() {
}

func (x *ListRoleResponse) Default() {
}

func (x *AssignPermissionsToRoleRequest) Default() {
	if x.Mode == nil {
		v := string("override")
		x.Mode = &v
	}
}

func (x *AssignPermissionsToRoleResponse) Default() {
}

func (x *GetRolePermissionsRequest) Default() {
}

func (x *GetRolePermissionsResponse) Default() {
}

func (x *PermissionTree) Default() {
}
