// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.0
// source: apiserver/v1/scheduled_task.proto

package v1

import (
	_ "github.com/onexstack/protoc-gen-defaults/defaults"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScheduledTask 表示客户端可管理的定时任务信息。
type ScheduledTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty"`
	// name 表示定时任务名称。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// taskType 表示要投递的异步任务类型。
	TaskType string `protobuf:"bytes,3,opt,name=taskType,proto3" json:"taskType,omitempty"`
	// payload 表示任务入队时携带的 JSON 负载。
	Payload *structpb.Struct `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// cronExpr 表示五段式 Cron 表达式。
	CronExpr string `protobuf:"bytes,5,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`
	// queue 表示任务投递目标队列。
	Queue string `protobuf:"bytes,6,opt,name=queue,proto3" json:"queue,omitempty"`
	// enabled 表示定时任务是否启用。
	Enabled bool `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// timezone 表示该定时任务使用的时区。
	Timezone string `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// userID 表示定时任务所属用户 ID。
	UserID string `protobuf:"bytes,9,opt,name=userID,proto3" json:"userID,omitempty"`
	// nextRunTime 表示下一次预计触发时间。
	NextRunTime int64 `protobuf:"varint,10,opt,name=nextRunTime,proto3" json:"nextRunTime,omitempty"`
	// lastScheduledAt 表示最近一次调度时间。
	LastScheduledAt int64 `protobuf:"varint,11,opt,name=lastScheduledAt,proto3" json:"lastScheduledAt,omitempty"`
	// lastExecutionID 表示最近一次执行记录 ID。
	LastExecutionID string `protobuf:"bytes,12,opt,name=lastExecutionID,proto3" json:"lastExecutionID,omitempty"`
	// lastError 表示最近一次调度错误信息。
	LastError string `protobuf:"bytes,13,opt,name=lastError,proto3" json:"lastError,omitempty"`
	// createdAt 表示创建时间。
	CreatedAt int64 `protobuf:"varint,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示最后更新时间。
	UpdatedAt     int64 `protobuf:"varint,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledTask) Reset() {
	*x = ScheduledTask{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledTask) ProtoMessage() {}

func (x *ScheduledTask) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledTask.ProtoReflect.Descriptor instead.
func (*ScheduledTask) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduledTask) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

func (x *ScheduledTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduledTask) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ScheduledTask) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ScheduledTask) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *ScheduledTask) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ScheduledTask) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScheduledTask) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ScheduledTask) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ScheduledTask) GetNextRunTime() int64 {
	if x != nil {
		return x.NextRunTime
	}
	return 0
}

func (x *ScheduledTask) GetLastScheduledAt() int64 {
	if x != nil {
		return x.LastScheduledAt
	}
	return 0
}

func (x *ScheduledTask) GetLastExecutionID() string {
	if x != nil {
		return x.LastExecutionID
	}
	return ""
}

func (x *ScheduledTask) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ScheduledTask) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ScheduledTask) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// ScheduledTaskExecution 表示定时任务的一次执行记录。
type ScheduledTaskExecution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// executionID 表示执行记录 ID。
	ExecutionID string `protobuf:"bytes,1,opt,name=executionID,proto3" json:"executionID,omitempty"`
	// scheduledTaskID 表示对应的定时任务 ID。
	ScheduledTaskID string `protobuf:"bytes,2,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty"`
	// userID 表示定时任务所属用户 ID。
	UserID string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	// triggerType 表示触发执行的方式。
	TriggerType string `protobuf:"bytes,4,opt,name=triggerType,proto3" json:"triggerType,omitempty"`
	// scheduledAt 表示计划调度时间。
	ScheduledAt int64 `protobuf:"varint,5,opt,name=scheduledAt,proto3" json:"scheduledAt,omitempty"`
	// enqueuedAt 表示任务成功入队时间。
	EnqueuedAt int64 `protobuf:"varint,6,opt,name=enqueuedAt,proto3" json:"enqueuedAt,omitempty"`
	// asynqTaskID 表示异步队列中的任务 ID。
	AsynqTaskID string `protobuf:"bytes,7,opt,name=asynqTaskID,proto3" json:"asynqTaskID,omitempty"`
	// dispatchStatus 表示任务入队阶段状态。
	DispatchStatus string `protobuf:"bytes,8,opt,name=dispatchStatus,proto3" json:"dispatchStatus,omitempty"`
	// processStatus 表示任务处理阶段状态。
	ProcessStatus string `protobuf:"bytes,9,opt,name=processStatus,proto3" json:"processStatus,omitempty"`
	// attempt 表示当前处理尝试次数。
	Attempt int32 `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// errorMsg 表示执行失败时的错误信息。
	ErrorMsg string `protobuf:"bytes,11,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	// startedAt 表示任务开始处理时间。
	StartedAt int64 `protobuf:"varint,12,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	// finishedAt 表示任务结束处理时间。
	FinishedAt int64 `protobuf:"varint,13,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	// durationMs 表示任务处理耗时，单位为毫秒。
	DurationMs int64 `protobuf:"varint,14,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	// createdAt 表示创建时间。
	CreatedAt int64 `protobuf:"varint,15,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示最后更新时间。
	UpdatedAt     int64 `protobuf:"varint,16,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduledTaskExecution) Reset() {
	*x = ScheduledTaskExecution{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduledTaskExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduledTaskExecution) ProtoMessage() {}

func (x *ScheduledTaskExecution) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduledTaskExecution.ProtoReflect.Descriptor instead.
func (*ScheduledTaskExecution) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduledTaskExecution) GetExecutionID() string {
	if x != nil {
		return x.ExecutionID
	}
	return ""
}

func (x *ScheduledTaskExecution) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

func (x *ScheduledTaskExecution) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ScheduledTaskExecution) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *ScheduledTaskExecution) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *ScheduledTaskExecution) GetEnqueuedAt() int64 {
	if x != nil {
		return x.EnqueuedAt
	}
	return 0
}

func (x *ScheduledTaskExecution) GetAsynqTaskID() string {
	if x != nil {
		return x.AsynqTaskID
	}
	return ""
}

func (x *ScheduledTaskExecution) GetDispatchStatus() string {
	if x != nil {
		return x.DispatchStatus
	}
	return ""
}

func (x *ScheduledTaskExecution) GetProcessStatus() string {
	if x != nil {
		return x.ProcessStatus
	}
	return ""
}

func (x *ScheduledTaskExecution) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ScheduledTaskExecution) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ScheduledTaskExecution) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ScheduledTaskExecution) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

func (x *ScheduledTaskExecution) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScheduledTaskExecution) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ScheduledTaskExecution) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateScheduledTaskRequest 表示创建定时任务请求。
type CreateScheduledTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 表示定时任务名称。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// taskType 表示要投递的异步任务类型。
	TaskType string `protobuf:"bytes,2,opt,name=taskType,proto3" json:"taskType,omitempty"`
	// payload 表示任务入队时携带的 JSON 负载。
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// cronExpr 表示五段式 Cron 表达式。
	CronExpr string `protobuf:"bytes,4,opt,name=cronExpr,proto3" json:"cronExpr,omitempty"`
	// queue 表示任务投递目标队列。
	Queue string `protobuf:"bytes,5,opt,name=queue,proto3" json:"queue,omitempty"`
	// enabled 表示定时任务是否启用。
	Enabled bool `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// timezone 表示该定时任务使用的时区。
	Timezone      string `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduledTaskRequest) Reset() {
	*x = CreateScheduledTaskRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledTaskRequest) ProtoMessage() {}

func (x *CreateScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateScheduledTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateScheduledTaskRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *CreateScheduledTaskRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateScheduledTaskRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// CreateScheduledTaskResponse 表示创建定时任务响应。
type CreateScheduledTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示新创建的定时任务 ID。
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateScheduledTaskResponse) Reset() {
	*x = CreateScheduledTaskResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledTaskResponse) ProtoMessage() {}

func (x *CreateScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateScheduledTaskResponse) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

// UpdateScheduledTaskRequest 表示更新定时任务请求。
type UpdateScheduledTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	// @gotags: uri:"scheduledTaskID"
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty" uri:"scheduledTaskID"`
	// name 表示可选的定时任务名称。
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// payload 表示可选的任务 JSON 负载。
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// cronExpr 表示可选的五段式 Cron 表达式。
	CronExpr *string `protobuf:"bytes,4,opt,name=cronExpr,proto3,oneof" json:"cronExpr,omitempty"`
	// queue 表示可选的任务投递目标队列。
	Queue *string `protobuf:"bytes,5,opt,name=queue,proto3,oneof" json:"queue,omitempty"`
	// enabled 表示可选的启用状态。
	Enabled *bool `protobuf:"varint,6,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	// timezone 表示可选的任务时区。
	Timezone      *string `protobuf:"bytes,7,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduledTaskRequest) Reset() {
	*x = UpdateScheduledTaskRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledTaskRequest) ProtoMessage() {}

func (x *UpdateScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateScheduledTaskRequest) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateScheduledTaskRequest) GetCronExpr() string {
	if x != nil && x.CronExpr != nil {
		return *x.CronExpr
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetQueue() string {
	if x != nil && x.Queue != nil {
		return *x.Queue
	}
	return ""
}

func (x *UpdateScheduledTaskRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *UpdateScheduledTaskRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

// UpdateScheduledTaskResponse 表示更新定时任务响应。
type UpdateScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduledTaskResponse) Reset() {
	*x = UpdateScheduledTaskResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduledTaskResponse) ProtoMessage() {}

func (x *UpdateScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{5}
}

// DeleteScheduledTaskRequest 表示删除定时任务请求。
type DeleteScheduledTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	// @gotags: uri:"scheduledTaskID"
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty" uri:"scheduledTaskID"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteScheduledTaskRequest) Reset() {
	*x = DeleteScheduledTaskRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledTaskRequest) ProtoMessage() {}

func (x *DeleteScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteScheduledTaskRequest) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

// DeleteScheduledTaskResponse 表示删除定时任务响应。
type DeleteScheduledTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduledTaskResponse) Reset() {
	*x = DeleteScheduledTaskResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduledTaskResponse) ProtoMessage() {}

func (x *DeleteScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{7}
}

// GetScheduledTaskRequest 表示获取定时任务请求。
type GetScheduledTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	// @gotags: uri:"scheduledTaskID"
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty" uri:"scheduledTaskID"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetScheduledTaskRequest) Reset() {
	*x = GetScheduledTaskRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledTaskRequest) ProtoMessage() {}

func (x *GetScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*GetScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{8}
}

func (x *GetScheduledTaskRequest) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

// GetScheduledTaskResponse 表示获取定时任务响应。
type GetScheduledTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTask 表示返回的定时任务信息。
	ScheduledTask *ScheduledTask `protobuf:"bytes,1,opt,name=scheduledTask,proto3" json:"scheduledTask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduledTaskResponse) Reset() {
	*x = GetScheduledTaskResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledTaskResponse) ProtoMessage() {}

func (x *GetScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*GetScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{9}
}

func (x *GetScheduledTaskResponse) GetScheduledTask() *ScheduledTask {
	if x != nil {
		return x.ScheduledTask
	}
	return nil
}

// ListScheduledTasksRequest 表示定时任务列表请求。
type ListScheduledTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pageToken 表示分页游标，用于获取下一页数据。
	// @gotags: form:"page_token"
	PageToken string `protobuf:"bytes,1,opt,name=pageToken,proto3" json:"pageToken,omitempty" form:"page_token"`
	// pageSize 表示每页数量。
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty" form:"page_size"`
	// enabled 表示可选的启用状态筛选条件。
	// @gotags: form:"enabled"
	Enabled *bool `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty" form:"enabled"`
	// taskType 表示可选的任务类型筛选条件。
	// @gotags: form:"task_type"
	TaskType      *string `protobuf:"bytes,4,opt,name=taskType,proto3,oneof" json:"taskType,omitempty" form:"task_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksRequest) Reset() {
	*x = ListScheduledTasksRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksRequest) ProtoMessage() {}

func (x *ListScheduledTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{10}
}

func (x *ListScheduledTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListScheduledTasksRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListScheduledTasksRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListScheduledTasksRequest) GetTaskType() string {
	if x != nil && x.TaskType != nil {
		return *x.TaskType
	}
	return ""
}

// ListScheduledTasksResponse 表示定时任务列表响应。
type ListScheduledTasksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示符合条件的定时任务总数。
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// scheduledTasks 表示定时任务列表。
	ScheduledTasks []*ScheduledTask `protobuf:"bytes,2,rep,name=scheduledTasks,proto3" json:"scheduledTasks,omitempty"`
	// pageToken 表示分页游标；为空表示没有更多数据。
	PageToken     string `protobuf:"bytes,3,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTasksResponse) Reset() {
	*x = ListScheduledTasksResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTasksResponse) ProtoMessage() {}

func (x *ListScheduledTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTasksResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTasksResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{11}
}

func (x *ListScheduledTasksResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListScheduledTasksResponse) GetScheduledTasks() []*ScheduledTask {
	if x != nil {
		return x.ScheduledTasks
	}
	return nil
}

func (x *ListScheduledTasksResponse) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ToggleScheduledTaskRequest 表示切换定时任务启用状态请求。
type ToggleScheduledTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	// @gotags: uri:"scheduledTaskID"
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty" uri:"scheduledTaskID"`
	// enabled 表示目标启用状态。
	Enabled       bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleScheduledTaskRequest) Reset() {
	*x = ToggleScheduledTaskRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleScheduledTaskRequest) ProtoMessage() {}

func (x *ToggleScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*ToggleScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{12}
}

func (x *ToggleScheduledTaskRequest) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

func (x *ToggleScheduledTaskRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ToggleScheduledTaskResponse 表示切换定时任务启用状态响应。
type ToggleScheduledTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTask 表示切换后的定时任务信息。
	ScheduledTask *ScheduledTask `protobuf:"bytes,1,opt,name=scheduledTask,proto3" json:"scheduledTask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleScheduledTaskResponse) Reset() {
	*x = ToggleScheduledTaskResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleScheduledTaskResponse) ProtoMessage() {}

func (x *ToggleScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*ToggleScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleScheduledTaskResponse) GetScheduledTask() *ScheduledTask {
	if x != nil {
		return x.ScheduledTask
	}
	return nil
}

// TriggerScheduledTaskRequest 表示手动触发定时任务请求。
type TriggerScheduledTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	// @gotags: uri:"scheduledTaskID"
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty" uri:"scheduledTaskID"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TriggerScheduledTaskRequest) Reset() {
	*x = TriggerScheduledTaskRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduledTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduledTaskRequest) ProtoMessage() {}

func (x *TriggerScheduledTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduledTaskRequest.ProtoReflect.Descriptor instead.
func (*TriggerScheduledTaskRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerScheduledTaskRequest) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

// TriggerScheduledTaskResponse 表示手动触发定时任务响应。
type TriggerScheduledTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// executionID 表示本次手动触发创建的执行记录 ID。
	ExecutionID   string `protobuf:"bytes,1,opt,name=executionID,proto3" json:"executionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScheduledTaskResponse) Reset() {
	*x = TriggerScheduledTaskResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduledTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduledTaskResponse) ProtoMessage() {}

func (x *TriggerScheduledTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduledTaskResponse.ProtoReflect.Descriptor instead.
func (*TriggerScheduledTaskResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerScheduledTaskResponse) GetExecutionID() string {
	if x != nil {
		return x.ExecutionID
	}
	return ""
}

// ListScheduledTaskExecutionsRequest 表示定时任务执行记录列表请求。
type ListScheduledTaskExecutionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scheduledTaskID 表示定时任务 ID。
	// @gotags: uri:"scheduledTaskID"
	ScheduledTaskID string `protobuf:"bytes,1,opt,name=scheduledTaskID,proto3" json:"scheduledTaskID,omitempty" uri:"scheduledTaskID"`
	// pageToken 表示分页游标，用于获取下一页数据。
	// @gotags: form:"page_token"
	PageToken string `protobuf:"bytes,2,opt,name=pageToken,proto3" json:"pageToken,omitempty" form:"page_token"`
	// pageSize 表示每页数量。
	// @gotags: form:"page_size"
	PageSize int64 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty" form:"page_size"`
	// dispatchStatus 表示可选的入队阶段状态筛选条件。
	// @gotags: form:"dispatch_status"
	DispatchStatus *string `protobuf:"bytes,4,opt,name=dispatchStatus,proto3,oneof" json:"dispatchStatus,omitempty" form:"dispatch_status"`
	// processStatus 表示可选的处理阶段状态筛选条件。
	// @gotags: form:"process_status"
	ProcessStatus *string `protobuf:"bytes,5,opt,name=processStatus,proto3,oneof" json:"processStatus,omitempty" form:"process_status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTaskExecutionsRequest) Reset() {
	*x = ListScheduledTaskExecutionsRequest{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTaskExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTaskExecutionsRequest) ProtoMessage() {}

func (x *ListScheduledTaskExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTaskExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListScheduledTaskExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{16}
}

func (x *ListScheduledTaskExecutionsRequest) GetScheduledTaskID() string {
	if x != nil {
		return x.ScheduledTaskID
	}
	return ""
}

func (x *ListScheduledTaskExecutionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListScheduledTaskExecutionsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListScheduledTaskExecutionsRequest) GetDispatchStatus() string {
	if x != nil && x.DispatchStatus != nil {
		return *x.DispatchStatus
	}
	return ""
}

func (x *ListScheduledTaskExecutionsRequest) GetProcessStatus() string {
	if x != nil && x.ProcessStatus != nil {
		return *x.ProcessStatus
	}
	return ""
}

// ListScheduledTaskExecutionsResponse 表示定时任务执行记录列表响应。
type ListScheduledTaskExecutionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示符合条件的执行记录总数。
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// executions 表示执行记录列表。
	Executions []*ScheduledTaskExecution `protobuf:"bytes,2,rep,name=executions,proto3" json:"executions,omitempty"`
	// pageToken 表示分页游标；为空表示没有更多数据。
	PageToken     string `protobuf:"bytes,3,opt,name=pageToken,proto3" json:"pageToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduledTaskExecutionsResponse) Reset() {
	*x = ListScheduledTaskExecutionsResponse{}
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduledTaskExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduledTaskExecutionsResponse) ProtoMessage() {}

func (x *ListScheduledTaskExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_scheduled_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduledTaskExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListScheduledTaskExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_scheduled_task_proto_rawDescGZIP(), []int{17}
}

func (x *ListScheduledTaskExecutionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListScheduledTaskExecutionsResponse) GetExecutions() []*ScheduledTaskExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListScheduledTaskExecutionsResponse) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

var File_apiserver_v1_scheduled_task_proto protoreflect.FileDescriptor

const file_apiserver_v1_scheduled_task_proto_rawDesc = "" +
	"\n" +
	"!apiserver/v1/scheduled_task.proto\x12\fapiserver.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a,github.com/onexstack/defaults/defaults.proto\"\xec\x03\n" +
	"\rScheduledTask\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\btaskType\x18\x03 \x01(\tR\btaskType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1a\n" +
	"\bcronExpr\x18\x05 \x01(\tR\bcronExpr\x12\x14\n" +
	"\x05queue\x18\x06 \x01(\tR\x05queue\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12\x16\n" +
	"\x06userID\x18\t \x01(\tR\x06userID\x12 \n" +
	"\vnextRunTime\x18\n" +
	" \x01(\x03R\vnextRunTime\x12(\n" +
	"\x0flastScheduledAt\x18\v \x01(\x03R\x0flastScheduledAt\x12(\n" +
	"\x0flastExecutionID\x18\f \x01(\tR\x0flastExecutionID\x12\x1c\n" +
	"\tlastError\x18\r \x01(\tR\tlastError\x12\x1c\n" +
	"\tcreatedAt\x18\x0e \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0f \x01(\x03R\tupdatedAt\"\xa0\x04\n" +
	"\x16ScheduledTaskExecution\x12 \n" +
	"\vexecutionID\x18\x01 \x01(\tR\vexecutionID\x12(\n" +
	"\x0fscheduledTaskID\x18\x02 \x01(\tR\x0fscheduledTaskID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\x12 \n" +
	"\vtriggerType\x18\x04 \x01(\tR\vtriggerType\x12 \n" +
	"\vscheduledAt\x18\x05 \x01(\x03R\vscheduledAt\x12\x1e\n" +
	"\n" +
	"enqueuedAt\x18\x06 \x01(\x03R\n" +
	"enqueuedAt\x12 \n" +
	"\vasynqTaskID\x18\a \x01(\tR\vasynqTaskID\x12&\n" +
	"\x0edispatchStatus\x18\b \x01(\tR\x0edispatchStatus\x12$\n" +
	"\rprocessStatus\x18\t \x01(\tR\rprocessStatus\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12\x1a\n" +
	"\berrorMsg\x18\v \x01(\tR\berrorMsg\x12\x1c\n" +
	"\tstartedAt\x18\f \x01(\x03R\tstartedAt\x12\x1e\n" +
	"\n" +
	"finishedAt\x18\r \x01(\x03R\n" +
	"finishedAt\x12\x1e\n" +
	"\n" +
	"durationMs\x18\x0e \x01(\x03R\n" +
	"durationMs\x12\x1c\n" +
	"\tcreatedAt\x18\x0f \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x10 \x01(\x03R\tupdatedAt\"\x89\x02\n" +
	"\x1aCreateScheduledTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btaskType\x18\x02 \x01(\tR\btaskType\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1a\n" +
	"\bcronExpr\x18\x04 \x01(\tR\bcronExpr\x12\"\n" +
	"\x05queue\x18\x05 \x01(\tB\f\x9aI\tr\adefaultR\x05queue\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12.\n" +
	"\btimezone\x18\a \x01(\tB\x12\x9aI\x0fr\rAsia/ShanghaiR\btimezone\"G\n" +
	"\x1bCreateScheduledTaskResponse\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\"\xc7\x02\n" +
	"\x1aUpdateScheduledTaskRequest\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1f\n" +
	"\bcronExpr\x18\x04 \x01(\tH\x01R\bcronExpr\x88\x01\x01\x12\x19\n" +
	"\x05queue\x18\x05 \x01(\tH\x02R\x05queue\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x06 \x01(\bH\x03R\aenabled\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\a \x01(\tH\x04R\btimezone\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_cronExprB\b\n" +
	"\x06_queueB\n" +
	"\n" +
	"\b_enabledB\v\n" +
	"\t_timezone\"\x1d\n" +
	"\x1bUpdateScheduledTaskResponse\"F\n" +
	"\x1aDeleteScheduledTaskRequest\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\"\x1d\n" +
	"\x1bDeleteScheduledTaskResponse\"C\n" +
	"\x17GetScheduledTaskRequest\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\"]\n" +
	"\x18GetScheduledTaskResponse\x12A\n" +
	"\rscheduledTask\x18\x01 \x01(\v2\x1b.apiserver.v1.ScheduledTaskR\rscheduledTask\"\xae\x01\n" +
	"\x19ListScheduledTasksRequest\x12\x1c\n" +
	"\tpageToken\x18\x01 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x1f\n" +
	"\btaskType\x18\x04 \x01(\tH\x01R\btaskType\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\v\n" +
	"\t_taskType\"\x9f\x01\n" +
	"\x1aListScheduledTasksResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12C\n" +
	"\x0escheduledTasks\x18\x02 \x03(\v2\x1b.apiserver.v1.ScheduledTaskR\x0escheduledTasks\x12\x1c\n" +
	"\tpageToken\x18\x03 \x01(\tR\tpageToken\"`\n" +
	"\x1aToggleScheduledTaskRequest\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"`\n" +
	"\x1bToggleScheduledTaskResponse\x12A\n" +
	"\rscheduledTask\x18\x01 \x01(\v2\x1b.apiserver.v1.ScheduledTaskR\rscheduledTask\"G\n" +
	"\x1bTriggerScheduledTaskRequest\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\"@\n" +
	"\x1cTriggerScheduledTaskResponse\x12 \n" +
	"\vexecutionID\x18\x01 \x01(\tR\vexecutionID\"\x85\x02\n" +
	"\"ListScheduledTaskExecutionsRequest\x12(\n" +
	"\x0fscheduledTaskID\x18\x01 \x01(\tR\x0fscheduledTaskID\x12\x1c\n" +
	"\tpageToken\x18\x02 \x01(\tR\tpageToken\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12+\n" +
	"\x0edispatchStatus\x18\x04 \x01(\tH\x00R\x0edispatchStatus\x88\x01\x01\x12)\n" +
	"\rprocessStatus\x18\x05 \x01(\tH\x01R\rprocessStatus\x88\x01\x01B\x11\n" +
	"\x0f_dispatchStatusB\x10\n" +
	"\x0e_processStatus\"\xa9\x01\n" +
	"#ListScheduledTaskExecutionsResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12D\n" +
	"\n" +
	"executions\x18\x02 \x03(\v2$.apiserver.v1.ScheduledTaskExecutionR\n" +
	"executions\x12\x1c\n" +
	"\tpageToken\x18\x03 \x01(\tR\tpageTokenBDZBgithub.com/clin211/gin-enterprise-template/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_scheduled_task_proto_rawDescOnce sync.Once
	file_apiserver_v1_scheduled_task_proto_rawDescData []byte
)

func file_apiserver_v1_scheduled_task_proto_rawDescGZIP() []byte {
	file_apiserver_v1_scheduled_task_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_scheduled_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_scheduled_task_proto_rawDesc), len(file_apiserver_v1_scheduled_task_proto_rawDesc)))
	})
	return file_apiserver_v1_scheduled_task_proto_rawDescData
}

var file_apiserver_v1_scheduled_task_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_apiserver_v1_scheduled_task_proto_goTypes = []any{
	(*ScheduledTask)(nil),                       // 0: apiserver.v1.ScheduledTask
	(*ScheduledTaskExecution)(nil),              // 1: apiserver.v1.ScheduledTaskExecution
	(*CreateScheduledTaskRequest)(nil),          // 2: apiserver.v1.CreateScheduledTaskRequest
	(*CreateScheduledTaskResponse)(nil),         // 3: apiserver.v1.CreateScheduledTaskResponse
	(*UpdateScheduledTaskRequest)(nil),          // 4: apiserver.v1.UpdateScheduledTaskRequest
	(*UpdateScheduledTaskResponse)(nil),         // 5: apiserver.v1.UpdateScheduledTaskResponse
	(*DeleteScheduledTaskRequest)(nil),          // 6: apiserver.v1.DeleteScheduledTaskRequest
	(*DeleteScheduledTaskResponse)(nil),         // 7: apiserver.v1.DeleteScheduledTaskResponse
	(*GetScheduledTaskRequest)(nil),             // 8: apiserver.v1.GetScheduledTaskRequest
	(*GetScheduledTaskResponse)(nil),            // 9: apiserver.v1.GetScheduledTaskResponse
	(*ListScheduledTasksRequest)(nil),           // 10: apiserver.v1.ListScheduledTasksRequest
	(*ListScheduledTasksResponse)(nil),          // 11: apiserver.v1.ListScheduledTasksResponse
	(*ToggleScheduledTaskRequest)(nil),          // 12: apiserver.v1.ToggleScheduledTaskRequest
	(*ToggleScheduledTaskResponse)(nil),         // 13: apiserver.v1.ToggleScheduledTaskResponse
	(*TriggerScheduledTaskRequest)(nil),         // 14: apiserver.v1.TriggerScheduledTaskRequest
	(*TriggerScheduledTaskResponse)(nil),        // 15: apiserver.v1.TriggerScheduledTaskResponse
	(*ListScheduledTaskExecutionsRequest)(nil),  // 16: apiserver.v1.ListScheduledTaskExecutionsRequest
	(*ListScheduledTaskExecutionsResponse)(nil), // 17: apiserver.v1.ListScheduledTaskExecutionsResponse
	(*structpb.Struct)(nil),                     // 18: google.protobuf.Struct
}
var file_apiserver_v1_scheduled_task_proto_depIdxs = []int32{
	18, // 0: apiserver.v1.ScheduledTask.payload:type_name -> google.protobuf.Struct
	18, // 1: apiserver.v1.CreateScheduledTaskRequest.payload:type_name -> google.protobuf.Struct
	18, // 2: apiserver.v1.UpdateScheduledTaskRequest.payload:type_name -> google.protobuf.Struct
	0,  // 3: apiserver.v1.GetScheduledTaskResponse.scheduledTask:type_name -> apiserver.v1.ScheduledTask
	0,  // 4: apiserver.v1.ListScheduledTasksResponse.scheduledTasks:type_name -> apiserver.v1.ScheduledTask
	0,  // 5: apiserver.v1.ToggleScheduledTaskResponse.scheduledTask:type_name -> apiserver.v1.ScheduledTask
	1,  // 6: apiserver.v1.ListScheduledTaskExecutionsResponse.executions:type_name -> apiserver.v1.ScheduledTaskExecution
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_apiserver_v1_scheduled_task_proto_init() }
func file_apiserver_v1_scheduled_task_proto_init() {
	if File_apiserver_v1_scheduled_task_proto != nil {
		return
	}
	file_apiserver_v1_scheduled_task_proto_msgTypes[4].OneofWrappers = []any{}
	file_apiserver_v1_scheduled_task_proto_msgTypes[10].OneofWrappers = []any{}
	file_apiserver_v1_scheduled_task_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_scheduled_task_proto_rawDesc), len(file_apiserver_v1_scheduled_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_scheduled_task_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_scheduled_task_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_scheduled_task_proto_msgTypes,
	}.Build()
	File_apiserver_v1_scheduled_task_proto = out.File
	file_apiserver_v1_scheduled_task_proto_goTypes = nil
	file_apiserver_v1_scheduled_task_proto_depIdxs = nil
}
