// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *ScheduledTask) Default() {
}

func (x *ScheduledTaskExecution) Default() {
}

func (x *CreateScheduledTaskRequest) Default() {
	if x.Queue == "" {
		x.Queue = "default"
	}
	if x.Timezone == "" {
		x.Timezone = "Asia/Shanghai"
	}
}

func (x *CreateScheduledTaskResponse) Default() {
}

func (x *UpdateScheduledTaskRequest) Default() {
}

func (x *UpdateScheduledTaskResponse) Default() {
}

func (x *DeleteScheduledTaskRequest) Default() {
}

func (x *DeleteScheduledTaskResponse) Default() {
}

func (x *GetScheduledTaskRequest) Default() {
}

func (x *GetScheduledTaskResponse) Default() {
}

func (x *ListScheduledTasksRequest) Default() {
}

func (x *ListScheduledTasksResponse) Default() {
}

func (x *ToggleScheduledTaskRequest) Default() {
}

func (x *ToggleScheduledTaskResponse) Default() {
}

func (x *TriggerScheduledTaskRequest) Default() {
}

func (x *TriggerScheduledTaskResponse) Default() {
}

func (x *ListScheduledTaskExecutionsRequest) Default() {
}

func (x *ListScheduledTaskExecutionsResponse) Default() {
}
